// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: a2da08625f57e4bae475887678df1065efceee7b
// Brief updated: 2026-04-27T13:04:10+03:00
//
// Style reference inspired by Bugatti's publicly visible design system.
// Hex Core is not affiliated with, endorsed by, or sponsored by Bugatti.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const bugattiTheme: Theme = {
	name: "bugatti",
	displayName: "Bugatti",
	description: "Hypercar brand. Cinema-black canvas, monochrome austerity, monumental display type.",
	category: "automotive",
	tags: ["automotive"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Bugatti",
	},
	tokens: {
		light: {
			background: { value: "0 0% 100%", type: "color" },
			foreground: { value: "240 10% 4%", type: "color" },
			card: { value: "0 0% 100%", type: "color" },
			"card-foreground": { value: "240 10% 4%", type: "color" },
			popover: { value: "0 0% 100%", type: "color" },
			"popover-foreground": { value: "240 10% 4%", type: "color" },
			primary: { value: "0 0% 100%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			secondary: { value: "0 0% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "0 0% 95.9%", type: "color" },
			"muted-foreground": { value: "240 8% 38%", type: "color" },
			accent: { value: "0 0% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "43 80.4% 46.1%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "240 8% 90%", type: "color" },
			input: { value: "240 8% 90%", type: "color" },
			ring: { value: "0 0% 100%", type: "color" },
			radius: { value: "0.25rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 0%", type: "color" },
			foreground: { value: "240 7.5% 96%", type: "color" },
			card: { value: "0 0% 0%", type: "color" },
			popover: { value: "0 0% 0%", type: "color" },
			primary: { value: "0 0% 0%", type: "color" },
			secondary: { value: "0 0% 4.1%", type: "color" },
			muted: { value: "0 0% 4.1%", type: "color" },
			accent: { value: "0 0% 4.1%", type: "color" },
			destructive: { value: "43 60.3% 53.9%", type: "color" },
			border: { value: "240 6% 10%", type: "color" },
			input: { value: "240 6% 10%", type: "color" },
			ring: { value: "0 0% 0%", type: "color" },
			radius: { value: "0.25rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			...sharedTokens,
		},
	},
};
