// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: 61d54ef44a5e118c5c4a6b81fb00861911fa6908
// Brief updated: 2026-04-28T16:10:34+03:00
//
// Style reference inspired by Coinbase's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by Coinbase.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const coinbaseTheme: Theme = {
	name: "coinbase",
	displayName: "Coinbase",
	description: "Crypto exchange. Clean blue identity, trust-focused, institutional feel.",
	category: "fintech",
	tags: ["fintech"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Coinbase",
	},
	tokens: {
		light: {
			background: { value: "0 0% 100%", type: "color" },
			foreground: { value: "220 13% 4.5%", type: "color" },
			card: { value: "0 0% 100%", type: "color" },
			"card-foreground": { value: "220 13% 4.5%", type: "color" },
			popover: { value: "0 0% 100%", type: "color" },
			"popover-foreground": { value: "220 13% 4.5%", type: "color" },
			primary: { value: "221 100% 50%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "221 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "221 5% 95.9%", type: "color" },
			"muted-foreground": { value: "220 8% 38%", type: "color" },
			accent: { value: "221 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "355 73.2% 46.9%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "220 8% 90%", type: "color" },
			input: { value: "220 8% 90%", type: "color" },
			ring: { value: "221 100% 50%", type: "color" },
			radius: { value: "1.5rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 0%", type: "color" },
			foreground: { value: "220 9.8% 95.5%", type: "color" },
			card: { value: "0 0% 0%", type: "color" },
			popover: { value: "0 0% 0%", type: "color" },
			primary: { value: "221 75% 50%", type: "color" },
			secondary: { value: "221 3.8% 4.1%", type: "color" },
			muted: { value: "221 3.8% 4.1%", type: "color" },
			accent: { value: "221 3.8% 4.1%", type: "color" },
			destructive: { value: "355 54.9% 53.1%", type: "color" },
			border: { value: "220 6% 10%", type: "color" },
			input: { value: "220 6% 10%", type: "color" },
			ring: { value: "221 75% 50%", type: "color" },
			radius: { value: "1.5rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 100%", type: "color" },
			...sharedTokens,
		},
	},
};
