// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: 61d54ef44a5e118c5c4a6b81fb00861911fa6908
// Brief updated: 2026-04-28T16:10:34+03:00
//
// Style reference inspired by Composio's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by Composio.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const composioTheme: Theme = {
	name: "composio",
	displayName: "Composio",
	description: "Tool integration platform. Modern dark with colorful integration icons.",
	category: "backend",
	tags: ["backend"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Composio",
	},
	tokens: {
		light: {
			background: { value: "0 0% 5.9%", type: "color" },
			foreground: { value: "0 0% 100%", type: "color" },
			card: { value: "0 0% 5.9%", type: "color" },
			"card-foreground": { value: "0 0% 100%", type: "color" },
			popover: { value: "0 0% 5.9%", type: "color" },
			"popover-foreground": { value: "0 0% 100%", type: "color" },
			primary: { value: "238 100% 40.2%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "238 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "238 5% 95.9%", type: "color" },
			"muted-foreground": { value: "0 0% 38%", type: "color" },
			accent: { value: "238 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "0 100% 65.1%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "0 0% 90%", type: "color" },
			input: { value: "0 0% 90%", type: "color" },
			ring: { value: "238 100% 40.2%", type: "color" },
			radius: { value: "2rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 94.1%", type: "color" },
			foreground: { value: "0 0% 0%", type: "color" },
			card: { value: "0 0% 94.1%", type: "color" },
			popover: { value: "0 0% 94.1%", type: "color" },
			primary: { value: "238 75% 59.8%", type: "color" },
			secondary: { value: "238 3.8% 4.1%", type: "color" },
			muted: { value: "238 3.8% 4.1%", type: "color" },
			accent: { value: "238 3.8% 4.1%", type: "color" },
			destructive: { value: "0 75% 34.9%", type: "color" },
			border: { value: "0 0% 10%", type: "color" },
			input: { value: "0 0% 10%", type: "color" },
			ring: { value: "238 75% 59.8%", type: "color" },
			radius: { value: "2rem", type: "radius" },
			"card-foreground": { value: "240 10% 3.9%", type: "color" },
			"popover-foreground": { value: "240 10% 3.9%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
