// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: 61d54ef44a5e118c5c4a6b81fb00861911fa6908
// Brief updated: 2026-04-28T16:10:34+03:00
//
// Style reference inspired by Cursor's publicly visible design system.
// Hex Core is not affiliated with, endorsed by, or sponsored by Cursor.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const cursorTheme: Theme = {
	name: "cursor",
	displayName: "Cursor",
	description: "AI-first code editor. Sleek dark interface, gradient accents.",
	category: "dev-tools",
	tags: ["dev-tools"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Cursor",
	},
	tokens: {
		light: {
			background: { value: "60 23.1% 97.5%", type: "color" },
			foreground: { value: "53 11.8% 13.3%", type: "color" },
			card: { value: "60 23.1% 97.5%", type: "color" },
			"card-foreground": { value: "53 11.8% 13.3%", type: "color" },
			popover: { value: "60 23.1% 97.5%", type: "color" },
			"popover-foreground": { value: "53 11.8% 13.3%", type: "color" },
			primary: { value: "19 100% 48%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			secondary: { value: "19 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "19 5% 95.9%", type: "color" },
			"muted-foreground": { value: "53 8% 38%", type: "color" },
			accent: { value: "19 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "345 64.3% 49.4%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "53 8% 90%", type: "color" },
			input: { value: "53 8% 90%", type: "color" },
			ring: { value: "19 100% 48%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "60 17.3% 2.5%", type: "color" },
			foreground: { value: "53 8.9% 86.7%", type: "color" },
			card: { value: "60 17.3% 2.5%", type: "color" },
			popover: { value: "60 17.3% 2.5%", type: "color" },
			primary: { value: "19 75% 52%", type: "color" },
			secondary: { value: "19 3.8% 4.1%", type: "color" },
			muted: { value: "19 3.8% 4.1%", type: "color" },
			accent: { value: "19 3.8% 4.1%", type: "color" },
			destructive: { value: "345 48.2% 50.6%", type: "color" },
			border: { value: "53 6% 10%", type: "color" },
			input: { value: "53 6% 10%", type: "color" },
			ring: { value: "19 75% 52%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
