// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: 61d54ef44a5e118c5c4a6b81fb00861911fa6908
// Brief updated: 2026-04-28T16:10:34+03:00
//
// Style reference inspired by ElevenLabs's publicly visible design system.
// Hex Core is not affiliated with, endorsed by, or sponsored by ElevenLabs.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const elevenlabsTheme: Theme = {
	name: "elevenlabs",
	displayName: "ElevenLabs",
	description: "AI voice platform. Dark cinematic UI, audio-waveform aesthetics.",
	category: "ai",
	tags: ["ai"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "ElevenLabs",
	},
	tokens: {
		light: {
			background: { value: "0 0% 96.1%", type: "color" },
			foreground: { value: "20 14.3% 4.1%", type: "color" },
			card: { value: "0 0% 96.1%", type: "color" },
			"card-foreground": { value: "20 14.3% 4.1%", type: "color" },
			popover: { value: "0 0% 96.1%", type: "color" },
			"popover-foreground": { value: "20 14.3% 4.1%", type: "color" },
			primary: { value: "12 6.5% 15.1%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "12 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "12 5% 95.9%", type: "color" },
			"muted-foreground": { value: "20 8% 38%", type: "color" },
			accent: { value: "12 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "0 72.2% 50.6%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "20 8% 90%", type: "color" },
			input: { value: "20 8% 90%", type: "color" },
			ring: { value: "12 6.5% 15.1%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 3.9%", type: "color" },
			foreground: { value: "20 10.7% 95.9%", type: "color" },
			card: { value: "0 0% 3.9%", type: "color" },
			popover: { value: "0 0% 3.9%", type: "color" },
			primary: { value: "12 4.9% 84.9%", type: "color" },
			secondary: { value: "12 3.8% 4.1%", type: "color" },
			muted: { value: "12 3.8% 4.1%", type: "color" },
			accent: { value: "12 3.8% 4.1%", type: "color" },
			destructive: { value: "0 54.1% 49.4%", type: "color" },
			border: { value: "20 6% 10%", type: "color" },
			input: { value: "20 6% 10%", type: "color" },
			ring: { value: "12 4.9% 84.9%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
