// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by HashiCorp's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by HashiCorp.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const hashicorpTheme: Theme = {
	name: "hashicorp",
	displayName: "HashiCorp",
	description: "Infrastructure automation. Enterprise-clean, black and white.",
	category: "backend",
	tags: ["backend"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "HashiCorp",
	},
	tokens: {
		light: {
			background: { value: "210 7.7% 94.9%", type: "color" },
			foreground: { value: "240 10% 4%", type: "color" },
			card: { value: "210 7.7% 94.9%", type: "color" },
			"card-foreground": { value: "240 10% 4%", type: "color" },
			popover: { value: "210 7.7% 94.9%", type: "color" },
			"popover-foreground": { value: "240 10% 4%", type: "color" },
			primary: { value: "0 0% 0%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "0 0% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "0 0% 95.9%", type: "color" },
			"muted-foreground": { value: "240 8% 38%", type: "color" },
			accent: { value: "0 0% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "355 58.6% 28.4%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "240 8% 90%", type: "color" },
			input: { value: "240 8% 90%", type: "color" },
			ring: { value: "0 0% 0%", type: "color" },
			radius: { value: "0.125rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "210 5.8% 5.1%", type: "color" },
			foreground: { value: "240 7.5% 96%", type: "color" },
			card: { value: "210 5.8% 5.1%", type: "color" },
			popover: { value: "210 5.8% 5.1%", type: "color" },
			primary: { value: "0 0% 100%", type: "color" },
			secondary: { value: "0 0% 4.1%", type: "color" },
			muted: { value: "0 0% 4.1%", type: "color" },
			accent: { value: "0 0% 4.1%", type: "color" },
			destructive: { value: "355 44% 71.6%", type: "color" },
			border: { value: "240 6% 10%", type: "color" },
			input: { value: "240 6% 10%", type: "color" },
			ring: { value: "0 0% 100%", type: "color" },
			radius: { value: "0.125rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			...sharedTokens,
		},
	},
};
