// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: a5d0fd2b949eabae5af3caaa2640af48b05004ff
// Brief updated: 2026-04-16T11:35:45+03:00
//
// Style reference inspired by Mastercard's publicly visible design system.
// Hex Core is not affiliated with, endorsed by, or sponsored by Mastercard.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const mastercardTheme: Theme = {
	name: "mastercard",
	displayName: "Mastercard",
	description: "Global payments network. Warm cream canvas, orbital pill shapes, editorial warmth.",
	category: "fintech",
	tags: ["fintech"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Mastercard",
	},
	tokens: {
		light: {
			background: { value: "24 17.2% 94.3%", type: "color" },
			foreground: { value: "60 2.6% 7.6%", type: "color" },
			card: { value: "24 17.2% 94.3%", type: "color" },
			"card-foreground": { value: "60 2.6% 7.6%", type: "color" },
			popover: { value: "24 17.2% 94.3%", type: "color" },
			"popover-foreground": { value: "60 2.6% 7.6%", type: "color" },
			primary: { value: "60 2.6% 7.6%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "60 2.6% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "60 2.6% 95.9%", type: "color" },
			"muted-foreground": { value: "60 2.6% 38%", type: "color" },
			accent: { value: "60 2.6% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "353 100% 46.1%", type: "color" },
			"destructive-foreground": { value: "0 0% 100%", type: "color" },
			border: { value: "60 2.6% 90%", type: "color" },
			input: { value: "60 2.6% 90%", type: "color" },
			ring: { value: "60 2.6% 7.6%", type: "color" },
			radius: { value: "2rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "24 12.9% 5.7%", type: "color" },
			foreground: { value: "60 2% 92.4%", type: "color" },
			card: { value: "24 12.9% 5.7%", type: "color" },
			popover: { value: "24 12.9% 5.7%", type: "color" },
			primary: { value: "60 2% 92.4%", type: "color" },
			secondary: { value: "60 2% 4.1%", type: "color" },
			muted: { value: "60 2% 4.1%", type: "color" },
			accent: { value: "60 2% 4.1%", type: "color" },
			destructive: { value: "353 75% 53.9%", type: "color" },
			border: { value: "60 2% 10%", type: "color" },
			input: { value: "60 2% 10%", type: "color" },
			ring: { value: "60 2% 92.4%", type: "color" },
			radius: { value: "2rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			...sharedTokens,
		},
	},
};
