// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by Miro's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by Miro.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const miroTheme: Theme = {
	name: "miro",
	displayName: "Miro",
	description: "Visual collaboration. Bright yellow accent, infinite canvas aesthetic.",
	category: "design",
	tags: ["design"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Miro",
	},
	tokens: {
		light: {
			background: { value: "0 0% 100%", type: "color" },
			foreground: { value: "240 3.4% 11.4%", type: "color" },
			card: { value: "0 0% 100%", type: "color" },
			"card-foreground": { value: "240 3.4% 11.4%", type: "color" },
			popover: { value: "0 0% 100%", type: "color" },
			"popover-foreground": { value: "240 3.4% 11.4%", type: "color" },
			primary: { value: "230 62.5% 43.9%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "230 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "230 5% 95.9%", type: "color" },
			"muted-foreground": { value: "240 3.4% 38%", type: "color" },
			accent: { value: "230 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "0 83% 90.8%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "240 3.4% 90%", type: "color" },
			input: { value: "240 3.4% 90%", type: "color" },
			ring: { value: "230 62.5% 43.9%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 0%", type: "color" },
			foreground: { value: "240 2.6% 88.6%", type: "color" },
			card: { value: "0 0% 0%", type: "color" },
			popover: { value: "0 0% 0%", type: "color" },
			primary: { value: "230 46.9% 56.1%", type: "color" },
			secondary: { value: "230 3.8% 4.1%", type: "color" },
			muted: { value: "230 3.8% 4.1%", type: "color" },
			accent: { value: "230 3.8% 4.1%", type: "color" },
			destructive: { value: "0 62.2% 9.2%", type: "color" },
			border: { value: "240 2.6% 10%", type: "color" },
			input: { value: "240 2.6% 10%", type: "color" },
			ring: { value: "230 46.9% 56.1%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
