// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by Mistral's publicly visible design system.
// Hex Core is not affiliated with, endorsed by, or sponsored by Mistral.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const mistralTheme: Theme = {
	name: "mistral",
	displayName: "Mistral",
	description: "Open-weight LLM provider. French-engineered minimalism, purple-toned.",
	category: "ai",
	tags: ["ai"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Mistral",
	},
	tokens: {
		light: {
			background: { value: "45 100% 96.1%", type: "color" },
			foreground: { value: "0 0% 12.2%", type: "color" },
			card: { value: "45 100% 96.1%", type: "color" },
			"card-foreground": { value: "0 0% 12.2%", type: "color" },
			popover: { value: "45 100% 96.1%", type: "color" },
			"popover-foreground": { value: "0 0% 12.2%", type: "color" },
			primary: { value: "17 95.9% 52%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			secondary: { value: "17 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "17 5% 95.9%", type: "color" },
			"muted-foreground": { value: "0 0% 38%", type: "color" },
			accent: { value: "17 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "17 95.9% 52%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "0 0% 90%", type: "color" },
			input: { value: "0 0% 90%", type: "color" },
			ring: { value: "17 95.9% 52%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "45 75% 3.9%", type: "color" },
			foreground: { value: "0 0% 87.8%", type: "color" },
			card: { value: "45 75% 3.9%", type: "color" },
			popover: { value: "45 75% 3.9%", type: "color" },
			primary: { value: "17 71.9% 48%", type: "color" },
			secondary: { value: "17 3.8% 4.1%", type: "color" },
			muted: { value: "17 3.8% 4.1%", type: "color" },
			accent: { value: "17 3.8% 4.1%", type: "color" },
			destructive: { value: "17 71.9% 48%", type: "color" },
			border: { value: "0 0% 10%", type: "color" },
			input: { value: "0 0% 10%", type: "color" },
			ring: { value: "17 71.9% 48%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			...sharedTokens,
		},
	},
};
