// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by NVIDIA's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by NVIDIA.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const nvidiaTheme: Theme = {
	name: "nvidia",
	displayName: "NVIDIA",
	description: "GPU computing. Green-black energy, technical power aesthetic.",
	category: "media",
	tags: ["media"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "NVIDIA",
	},
	tokens: {
		light: {
			background: { value: "0 0% 0%", type: "color" },
			foreground: { value: "27 100% 43.7%", type: "color" },
			card: { value: "0 0% 0%", type: "color" },
			"card-foreground": { value: "27 100% 43.7%", type: "color" },
			popover: { value: "0 0% 0%", type: "color" },
			"popover-foreground": { value: "27 100% 43.7%", type: "color" },
			primary: { value: "82 100% 36.3%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			secondary: { value: "82 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "82 5% 95.9%", type: "color" },
			"muted-foreground": { value: "27 8% 38%", type: "color" },
			accent: { value: "82 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "0 79.1% 51.2%", type: "color" },
			"destructive-foreground": { value: "0 0% 100%", type: "color" },
			border: { value: "27 8% 90%", type: "color" },
			input: { value: "27 8% 90%", type: "color" },
			ring: { value: "82 100% 36.3%", type: "color" },
			radius: { value: "0.125rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 100%", type: "color" },
			foreground: { value: "240 10% 3.9%", type: "color" },
			card: { value: "0 0% 100%", type: "color" },
			popover: { value: "0 0% 100%", type: "color" },
			primary: { value: "82 75% 63.7%", type: "color" },
			secondary: { value: "82 3.8% 4.1%", type: "color" },
			muted: { value: "82 3.8% 4.1%", type: "color" },
			accent: { value: "82 3.8% 4.1%", type: "color" },
			destructive: { value: "0 59.3% 48.8%", type: "color" },
			border: { value: "27 6% 10%", type: "color" },
			input: { value: "27 6% 10%", type: "color" },
			ring: { value: "82 75% 63.7%", type: "color" },
			radius: { value: "0.125rem", type: "radius" },
			"card-foreground": { value: "240 10% 3.9%", type: "color" },
			"popover-foreground": { value: "240 10% 3.9%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
