// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by OpenCode's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by OpenCode.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const opencodeTheme: Theme = {
	name: "opencode",
	displayName: "OpenCode",
	description: "AI coding platform. Developer-centric dark theme.",
	category: "ai",
	tags: ["ai"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "OpenCode",
	},
	tokens: {
		light: {
			background: { value: "0 9.7% 93.9%", type: "color" },
			foreground: { value: "240 10% 4%", type: "color" },
			card: { value: "0 9.7% 93.9%", type: "color" },
			"card-foreground": { value: "240 10% 4%", type: "color" },
			popover: { value: "0 9.7% 93.9%", type: "color" },
			"popover-foreground": { value: "240 10% 4%", type: "color" },
			primary: { value: "211 100% 50%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			secondary: { value: "211 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "211 5% 95.9%", type: "color" },
			"muted-foreground": { value: "240 8% 38%", type: "color" },
			accent: { value: "211 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "3 100% 59.4%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "240 8% 90%", type: "color" },
			input: { value: "240 8% 90%", type: "color" },
			ring: { value: "211 100% 50%", type: "color" },
			radius: { value: "0.25rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 7.3% 6.1%", type: "color" },
			foreground: { value: "240 7.5% 96%", type: "color" },
			card: { value: "0 7.3% 6.1%", type: "color" },
			popover: { value: "0 7.3% 6.1%", type: "color" },
			primary: { value: "211 75% 50%", type: "color" },
			secondary: { value: "211 3.8% 4.1%", type: "color" },
			muted: { value: "211 3.8% 4.1%", type: "color" },
			accent: { value: "211 3.8% 4.1%", type: "color" },
			destructive: { value: "3 75% 40.6%", type: "color" },
			border: { value: "240 6% 10%", type: "color" },
			input: { value: "240 6% 10%", type: "color" },
			ring: { value: "211 75% 50%", type: "color" },
			radius: { value: "0.25rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
