// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by Pinterest's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by Pinterest.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const pinterestTheme: Theme = {
	name: "pinterest",
	displayName: "Pinterest",
	description: "Visual discovery. Red accent, masonry grid, image-first.",
	category: "media",
	tags: ["media"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Pinterest",
	},
	tokens: {
		light: {
			background: { value: "60 8.8% 88.8%", type: "color" },
			foreground: { value: "293 15.3% 11.6%", type: "color" },
			card: { value: "60 8.8% 88.8%", type: "color" },
			"card-foreground": { value: "293 15.3% 11.6%", type: "color" },
			popover: { value: "60 8.8% 88.8%", type: "color" },
			"popover-foreground": { value: "293 15.3% 11.6%", type: "color" },
			primary: { value: "351 100% 45.1%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "351 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "351 5% 95.9%", type: "color" },
			"muted-foreground": { value: "293 8% 38%", type: "color" },
			accent: { value: "351 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "0 88.1% 32.9%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "293 8% 90%", type: "color" },
			input: { value: "293 8% 90%", type: "color" },
			ring: { value: "351 100% 45.1%", type: "color" },
			radius: { value: "0.75rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "60 6.6% 11.2%", type: "color" },
			foreground: { value: "293 11.5% 88.4%", type: "color" },
			card: { value: "60 6.6% 11.2%", type: "color" },
			popover: { value: "60 6.6% 11.2%", type: "color" },
			primary: { value: "351 75% 54.9%", type: "color" },
			secondary: { value: "351 3.8% 4.1%", type: "color" },
			muted: { value: "351 3.8% 4.1%", type: "color" },
			accent: { value: "351 3.8% 4.1%", type: "color" },
			destructive: { value: "0 66.1% 67.1%", type: "color" },
			border: { value: "293 6% 10%", type: "color" },
			input: { value: "293 6% 10%", type: "color" },
			ring: { value: "351 75% 54.9%", type: "color" },
			radius: { value: "0.75rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			...sharedTokens,
		},
	},
};
