// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by Resend's publicly visible design system.
// Hex Core is not affiliated with, endorsed by, or sponsored by Resend.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const resendTheme: Theme = {
	name: "resend",
	displayName: "Resend",
	description: "Email API. Minimal dark theme, monospace accents.",
	category: "productivity",
	tags: ["productivity"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Resend",
	},
	tokens: {
		light: {
			background: { value: "0 0% 0%", type: "color" },
			foreground: { value: "0 0% 94.1%", type: "color" },
			card: { value: "0 0% 0%", type: "color" },
			"card-foreground": { value: "0 0% 94.1%", type: "color" },
			popover: { value: "0 0% 0%", type: "color" },
			"popover-foreground": { value: "0 0% 94.1%", type: "color" },
			primary: { value: "220 100% 99.4%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			secondary: { value: "220 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "220 5% 95.9%", type: "color" },
			"muted-foreground": { value: "0 0% 38%", type: "color" },
			accent: { value: "220 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "350 100% 56.3%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "0 0% 90%", type: "color" },
			input: { value: "0 0% 90%", type: "color" },
			ring: { value: "220 100% 99.4%", type: "color" },
			radius: { value: "2rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 100%", type: "color" },
			foreground: { value: "0 0% 5.9%", type: "color" },
			card: { value: "0 0% 100%", type: "color" },
			popover: { value: "0 0% 100%", type: "color" },
			primary: { value: "220 75% 0.6%", type: "color" },
			secondary: { value: "220 3.8% 4.1%", type: "color" },
			muted: { value: "220 3.8% 4.1%", type: "color" },
			accent: { value: "220 3.8% 4.1%", type: "color" },
			destructive: { value: "350 75% 43.7%", type: "color" },
			border: { value: "0 0% 10%", type: "color" },
			input: { value: "0 0% 10%", type: "color" },
			ring: { value: "220 75% 0.6%", type: "color" },
			radius: { value: "2rem", type: "radius" },
			"card-foreground": { value: "240 10% 3.9%", type: "color" },
			"popover-foreground": { value: "240 10% 3.9%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
