// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by Revolut's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by Revolut.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const revolutTheme: Theme = {
	name: "revolut",
	displayName: "Revolut",
	description: "Digital banking. Sleek dark interface, gradient cards, fintech precision.",
	category: "fintech",
	tags: ["fintech"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Revolut",
	},
	tokens: {
		light: {
			background: { value: "0 0% 95.7%", type: "color" },
			foreground: { value: "0 100% 27.3%", type: "color" },
			card: { value: "0 0% 95.7%", type: "color" },
			"card-foreground": { value: "0 100% 27.3%", type: "color" },
			popover: { value: "0 0% 95.7%", type: "color" },
			"popover-foreground": { value: "0 100% 27.3%", type: "color" },
			primary: { value: "238 70.1% 58%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "238 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "238 5% 95.9%", type: "color" },
			"muted-foreground": { value: "0 8% 38%", type: "color" },
			accent: { value: "238 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "355 74.2% 55.9%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "0 8% 90%", type: "color" },
			input: { value: "0 8% 90%", type: "color" },
			ring: { value: "238 70.1% 58%", type: "color" },
			radius: { value: "0.125rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 4.3%", type: "color" },
			foreground: { value: "0 75% 72.7%", type: "color" },
			card: { value: "0 0% 4.3%", type: "color" },
			popover: { value: "0 0% 4.3%", type: "color" },
			primary: { value: "238 52.6% 42%", type: "color" },
			secondary: { value: "238 3.8% 4.1%", type: "color" },
			muted: { value: "238 3.8% 4.1%", type: "color" },
			accent: { value: "238 3.8% 4.1%", type: "color" },
			destructive: { value: "355 55.6% 44.1%", type: "color" },
			border: { value: "0 6% 10%", type: "color" },
			input: { value: "0 6% 10%", type: "color" },
			ring: { value: "238 52.6% 42%", type: "color" },
			radius: { value: "0.125rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
