// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by Spotify's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by Spotify.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const spotifyTheme: Theme = {
	name: "spotify",
	displayName: "Spotify",
	description: "Music streaming. Vibrant green on dark, bold type, album-art-driven.",
	category: "media",
	tags: ["media"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Spotify",
	},
	tokens: {
		light: {
			background: { value: "0 0% 7.1%", type: "color" },
			foreground: { value: "0 0% 100%", type: "color" },
			card: { value: "0 0% 7.1%", type: "color" },
			"card-foreground": { value: "0 0% 100%", type: "color" },
			popover: { value: "0 0% 7.1%", type: "color" },
			"popover-foreground": { value: "0 0% 100%", type: "color" },
			primary: { value: "141 75.5% 48%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			secondary: { value: "141 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "141 5% 95.9%", type: "color" },
			"muted-foreground": { value: "0 0% 38%", type: "color" },
			accent: { value: "141 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "354 84.3% 70%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "0 0% 90%", type: "color" },
			input: { value: "0 0% 90%", type: "color" },
			ring: { value: "141 75.5% 48%", type: "color" },
			radius: { value: "2rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 92.9%", type: "color" },
			foreground: { value: "0 0% 0%", type: "color" },
			card: { value: "0 0% 92.9%", type: "color" },
			popover: { value: "0 0% 92.9%", type: "color" },
			primary: { value: "141 56.6% 52%", type: "color" },
			secondary: { value: "141 3.8% 4.1%", type: "color" },
			muted: { value: "141 3.8% 4.1%", type: "color" },
			accent: { value: "141 3.8% 4.1%", type: "color" },
			destructive: { value: "354 63.2% 30%", type: "color" },
			border: { value: "0 0% 10%", type: "color" },
			input: { value: "0 0% 10%", type: "color" },
			ring: { value: "141 56.6% 52%", type: "color" },
			radius: { value: "2rem", type: "radius" },
			"card-foreground": { value: "240 10% 3.9%", type: "color" },
			"popover-foreground": { value: "240 10% 3.9%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
