// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: aa962b9fe7cb2c95a037ce74b435559b2af279f4
// Brief updated: 2026-04-20T10:48:31+03:00
//
// Style reference inspired by Starbucks's publicly visible design system.
// Hex Core is not affiliated with, endorsed by, or sponsored by Starbucks.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const starbucksTheme: Theme = {
	name: "starbucks",
	displayName: "Starbucks",
	description: "Global coffee retail brand. Four-tier green system, warm cream canvas, full-pill buttons.",
	category: "ecommerce",
	tags: ["ecommerce"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Starbucks",
	},
	tokens: {
		light: {
			background: { value: "43 21.2% 93.5%", type: "color" },
			foreground: { value: "160 100% 19.2%", type: "color" },
			card: { value: "43 21.2% 93.5%", type: "color" },
			"card-foreground": { value: "160 100% 19.2%", type: "color" },
			popover: { value: "43 21.2% 93.5%", type: "color" },
			"popover-foreground": { value: "160 100% 19.2%", type: "color" },
			primary: { value: "158 100% 22.9%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "158 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "158 5% 95.9%", type: "color" },
			"muted-foreground": { value: "160 8% 38%", type: "color" },
			accent: { value: "158 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "4 81.8% 43.1%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "160 8% 90%", type: "color" },
			input: { value: "160 8% 90%", type: "color" },
			ring: { value: "158 100% 22.9%", type: "color" },
			radius: { value: "2rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "43 15.9% 6.5%", type: "color" },
			foreground: { value: "160 75% 80.8%", type: "color" },
			card: { value: "43 15.9% 6.5%", type: "color" },
			popover: { value: "43 15.9% 6.5%", type: "color" },
			primary: { value: "158 75% 77.1%", type: "color" },
			secondary: { value: "158 3.8% 4.1%", type: "color" },
			muted: { value: "158 3.8% 4.1%", type: "color" },
			accent: { value: "158 3.8% 4.1%", type: "color" },
			destructive: { value: "4 61.3% 56.9%", type: "color" },
			border: { value: "160 6% 10%", type: "color" },
			input: { value: "160 6% 10%", type: "color" },
			ring: { value: "158 75% 77.1%", type: "color" },
			radius: { value: "2rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			...sharedTokens,
		},
	},
};
