// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by Stripe's publicly visible design system.
// Hex Core is not affiliated with, endorsed by, or sponsored by Stripe.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const stripeTheme: Theme = {
	name: "stripe",
	displayName: "Stripe",
	description: "Payment infrastructure. Signature purple gradients, weight-300 elegance.",
	category: "fintech",
	tags: ["fintech","saturated","purple"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Stripe",
	},
	tokens: {
		light: {
			background: { value: "0 0% 100%", type: "color" },
			foreground: { value: "211 78.2% 10.8%", type: "color" },
			card: { value: "0 0% 100%", type: "color" },
			"card-foreground": { value: "211 78.2% 10.8%", type: "color" },
			popover: { value: "0 0% 100%", type: "color" },
			"popover-foreground": { value: "211 78.2% 10.8%", type: "color" },
			primary: { value: "248 98% 61%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "248 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "248 5% 95.9%", type: "color" },
			"muted-foreground": { value: "211 8% 38%", type: "color" },
			accent: { value: "248 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "341 82.6% 52.5%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "211 8% 90%", type: "color" },
			input: { value: "211 8% 90%", type: "color" },
			ring: { value: "248 98% 61%", type: "color" },
			radius: { value: "0.25rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 0%", type: "color" },
			foreground: { value: "211 58.7% 89.2%", type: "color" },
			card: { value: "0 0% 0%", type: "color" },
			popover: { value: "0 0% 0%", type: "color" },
			primary: { value: "248 73.5% 39%", type: "color" },
			secondary: { value: "248 3.8% 4.1%", type: "color" },
			muted: { value: "248 3.8% 4.1%", type: "color" },
			accent: { value: "248 3.8% 4.1%", type: "color" },
			destructive: { value: "341 61.9% 47.5%", type: "color" },
			border: { value: "211 6% 10%", type: "color" },
			input: { value: "211 6% 10%", type: "color" },
			ring: { value: "248 73.5% 39%", type: "color" },
			radius: { value: "0.25rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
