// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by Tesla's publicly visible design system.
// Hex Core is not affiliated with, endorsed by, or sponsored by Tesla.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const teslaTheme: Theme = {
	name: "tesla",
	displayName: "Tesla",
	description: "Electric automotive. Radical subtraction, full-viewport photography, near-zero UI.",
	category: "automotive",
	tags: ["minimalist","monochrome","automotive"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Tesla",
	},
	tokens: {
		light: {
			background: { value: "0 0% 100%", type: "color" },
			foreground: { value: "220 16.4% 10.8%", type: "color" },
			card: { value: "0 0% 100%", type: "color" },
			"card-foreground": { value: "220 16.4% 10.8%", type: "color" },
			popover: { value: "0 0% 100%", type: "color" },
			"popover-foreground": { value: "220 16.4% 10.8%", type: "color" },
			primary: { value: "224 73.1% 56.3%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "224 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "224 5% 95.9%", type: "color" },
			"muted-foreground": { value: "220 8% 38%", type: "color" },
			accent: { value: "224 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "0 65% 43%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "220 8% 90%", type: "color" },
			input: { value: "220 8% 90%", type: "color" },
			ring: { value: "224 73.1% 56.3%", type: "color" },
			radius: { value: "0.25rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 0%", type: "color" },
			foreground: { value: "220 12.3% 89.2%", type: "color" },
			card: { value: "0 0% 0%", type: "color" },
			popover: { value: "0 0% 0%", type: "color" },
			primary: { value: "224 54.8% 43.7%", type: "color" },
			secondary: { value: "224 3.8% 4.1%", type: "color" },
			muted: { value: "224 3.8% 4.1%", type: "color" },
			accent: { value: "224 3.8% 4.1%", type: "color" },
			destructive: { value: "0 48.8% 57%", type: "color" },
			border: { value: "220 6% 10%", type: "color" },
			input: { value: "220 6% 10%", type: "color" },
			ring: { value: "224 54.8% 43.7%", type: "color" },
			radius: { value: "0.25rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			...sharedTokens,
		},
	},
};
