// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: 8287eab37321eb75654f1b221134421601b3e278
// Brief updated: 2026-04-11T17:03:12+03:00
//
// Style reference inspired by The Verge's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by The Verge.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const thevergeTheme: Theme = {
	name: "theverge",
	displayName: "The Verge",
	description: "Tech editorial media. Acid-mint and ultraviolet accents, Manuka display, rave-flyer story tiles.",
	category: "media",
	tags: ["media"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "The Verge",
	},
	tokens: {
		light: {
			background: { value: "0 0% 7.5%", type: "color" },
			foreground: { value: "0 0% 100%", type: "color" },
			card: { value: "0 0% 7.5%", type: "color" },
			"card-foreground": { value: "0 0% 100%", type: "color" },
			popover: { value: "0 0% 7.5%", type: "color" },
			"popover-foreground": { value: "0 0% 100%", type: "color" },
			primary: { value: "166 100% 61.8%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			secondary: { value: "166 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "166 5% 95.9%", type: "color" },
			"muted-foreground": { value: "0 0% 38%", type: "color" },
			accent: { value: "166 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "0 0% 58%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "0 0% 90%", type: "color" },
			input: { value: "0 0% 90%", type: "color" },
			ring: { value: "166 100% 61.8%", type: "color" },
			radius: { value: "1.5rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "0 0% 92.5%", type: "color" },
			foreground: { value: "0 0% 0%", type: "color" },
			card: { value: "0 0% 92.5%", type: "color" },
			popover: { value: "0 0% 92.5%", type: "color" },
			primary: { value: "166 75% 38.2%", type: "color" },
			secondary: { value: "166 3.8% 4.1%", type: "color" },
			muted: { value: "166 3.8% 4.1%", type: "color" },
			accent: { value: "166 3.8% 4.1%", type: "color" },
			destructive: { value: "0 0% 42%", type: "color" },
			border: { value: "0 0% 10%", type: "color" },
			input: { value: "0 0% 10%", type: "color" },
			ring: { value: "166 75% 38.2%", type: "color" },
			radius: { value: "1.5rem", type: "radius" },
			"card-foreground": { value: "240 10% 3.9%", type: "color" },
			"popover-foreground": { value: "240 10% 3.9%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
