// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by VoltAgent's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by VoltAgent.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const voltagentTheme: Theme = {
	name: "voltagent",
	displayName: "VoltAgent",
	description: "AI agent framework. Void-black canvas, emerald accent, terminal-native.",
	category: "ai",
	tags: ["ai"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "VoltAgent",
	},
	tokens: {
		light: {
			background: { value: "240 16.7% 2.4%", type: "color" },
			foreground: { value: "0 0% 94.9%", type: "color" },
			card: { value: "240 16.7% 2.4%", type: "color" },
			"card-foreground": { value: "0 0% 94.9%", type: "color" },
			popover: { value: "240 16.7% 2.4%", type: "color" },
			"popover-foreground": { value: "0 0% 94.9%", type: "color" },
			primary: { value: "161 67.1% 51.2%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			secondary: { value: "161 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "161 5% 95.9%", type: "color" },
			"muted-foreground": { value: "0 0% 38%", type: "color" },
			accent: { value: "161 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "358 95.4% 66.1%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			border: { value: "0 0% 90%", type: "color" },
			input: { value: "0 0% 90%", type: "color" },
			ring: { value: "161 67.1% 51.2%", type: "color" },
			radius: { value: "0.375rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "240 12.5% 97.6%", type: "color" },
			foreground: { value: "0 0% 5.1%", type: "color" },
			card: { value: "240 12.5% 97.6%", type: "color" },
			popover: { value: "240 12.5% 97.6%", type: "color" },
			primary: { value: "161 50.3% 48.8%", type: "color" },
			secondary: { value: "161 3.8% 4.1%", type: "color" },
			muted: { value: "161 3.8% 4.1%", type: "color" },
			accent: { value: "161 3.8% 4.1%", type: "color" },
			destructive: { value: "358 71.5% 33.9%", type: "color" },
			border: { value: "0 0% 10%", type: "color" },
			input: { value: "0 0% 10%", type: "color" },
			ring: { value: "161 50.3% 48.8%", type: "color" },
			radius: { value: "0.375rem", type: "radius" },
			"card-foreground": { value: "240 10% 3.9%", type: "color" },
			"popover-foreground": { value: "240 10% 3.9%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
