// AUTO-GENERATED by scripts/import-voltagent.ts — do not hand-edit.
// Source: voltagent/awesome-design-md (MIT) — https://github.com/voltagent/awesome-design-md
// Brief commit: d2a7eb2d1e4ca5f5272be4bec46a5f35f7f01edd
// Brief updated: 2026-04-09T18:04:01+03:00
//
// Style reference inspired by Zapier's publicly visible design system.
// Hex UI is not affiliated with, endorsed by, or sponsored by Zapier.
// Re-run `pnpm import:themes` to regenerate from the latest briefs.
import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "@hex-core/tokens";

export const zapierTheme: Theme = {
	name: "zapier",
	displayName: "Zapier",
	description: "Automation platform. Warm orange, friendly illustration-driven.",
	category: "productivity",
	tags: ["productivity"],
	attribution: {
		source: "voltagent/awesome-design-md",
		license: "MIT",
		url: "https://github.com/voltagent/awesome-design-md",
		brand: "Zapier",
	},
	tokens: {
		light: {
			background: { value: "45 100% 99.2%", type: "color" },
			foreground: { value: "0 20.8% 10.4%", type: "color" },
			card: { value: "45 100% 99.2%", type: "color" },
			"card-foreground": { value: "0 20.8% 10.4%", type: "color" },
			popover: { value: "45 100% 99.2%", type: "color" },
			"popover-foreground": { value: "0 20.8% 10.4%", type: "color" },
			primary: { value: "19 100% 50%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			secondary: { value: "19 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "19 5% 95.9%", type: "color" },
			"muted-foreground": { value: "0 8% 38%", type: "color" },
			accent: { value: "19 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "0 20.8% 10.4%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "0 8% 90%", type: "color" },
			input: { value: "0 8% 90%", type: "color" },
			ring: { value: "19 100% 50%", type: "color" },
			radius: { value: "0.25rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "45 75% 0.8%", type: "color" },
			foreground: { value: "0 15.6% 89.6%", type: "color" },
			card: { value: "45 75% 0.8%", type: "color" },
			popover: { value: "45 75% 0.8%", type: "color" },
			primary: { value: "19 75% 50%", type: "color" },
			secondary: { value: "19 3.8% 4.1%", type: "color" },
			muted: { value: "19 3.8% 4.1%", type: "color" },
			accent: { value: "19 3.8% 4.1%", type: "color" },
			destructive: { value: "0 15.6% 89.6%", type: "color" },
			border: { value: "0 6% 10%", type: "color" },
			input: { value: "0 6% 10%", type: "color" },
			ring: { value: "19 75% 50%", type: "color" },
			radius: { value: "0.25rem", type: "radius" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 10% 3.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			"muted-foreground": { value: "0 0% 98%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			"destructive-foreground": { value: "240 10% 3.9%", type: "color" },
			...sharedTokens,
		},
	},
};
