/**
 * Schema re-exports — design-time metadata used by tooling that wants
 * typed access to the component manifest.
 *
 * Lives in its own entry so the runtime barrel (`@hex-core/components`)
 * does NOT pull in `@hex-core/registry`'s `ComponentSchemaDefinition`
 * type. With registry as an optional peer (1.4.0+), runtime consumers
 * shouldn't have to install registry just to get types for `<Button />`.
 * Tooling consumers import from `@hex-core/components/schemas` and
 * install `@hex-core/registry` alongside.
 *
 * Generated by `scripts/build-barrels.ts`. The hand-written version of
 * this file shipped 109 of 161 schemas — every block and both hooks were
 * missing, and nothing caught it because the registry build reads schema
 * files from disk rather than through this barrel.
 */
export * from "./schemas.generated.js";
