/**
 * Snapshot test for `buildFigmaTokens`. Runs as a standalone node script via
 * `pnpm -F \`@hex-core/payload\` test:figma-tokens`. No test runner — the function
 * is pure and a format change should fail loudly here so it can be reviewed
 * deliberately.
 *
 * To update the snapshot: run the test, copy the actual output from stderr,
 * and replace EXPECTED below. Treat each update as a public-API change to
 * the Figma payload format and bump the changeset accordingly (anything
 * downstream of Figma's API expects this exact shape).
 *
 * All output (success AND failure) writes to stderr; stdout stays empty so
 * piping this into another command stays clean.
 */

import { buildFigmaPayload, buildFigmaTokens, type FigmaTokensTheme } from "./figma-tokens.js";

const fakeTheme: FigmaTokensTheme = {
	name: "default",
	displayName: "Default",
	tokens: {
		// Mix of color + non-color tokens so both COLOR and FLOAT branches
		// are exercised. `radius` carries a rem unit (→ 8 in Figma's px float),
		// `duration-normal` carries `200ms` (→ 200), `space-4` carries `1rem` (→ 16).
		light: {
			background: { value: "0 0% 100%", type: "color" },
			primary: { value: "240 5.9% 10%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			"duration-normal": { value: "200ms", type: "duration" },
			"space-4": { value: "1rem", type: "spacing" },
		},
		dark: {
			background: { value: "240 10% 3.9%", type: "color" },
			primary: { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 5.9% 10%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			"duration-normal": { value: "200ms", type: "duration" },
			"space-4": { value: "1rem", type: "spacing" },
		},
	},
};

const EXPECTED_HAPPY = `# Figma tokens — Hex Core

Generated by \`emit_figma_tokens\`. Paste the JSON below into Figma's \`POST /v1/files/:file_key/variables\` endpoint (or a Figma plugin that calls it) to populate a Variables collection that mirrors the theme.

## Theme — Default \`default\`

Collection: **Hex Core — Default**. Modes: **Light** + **Dark**. Variables: **6** (3 COLOR, 3 FLOAT). Mode-values: **12**.

## Payload

\`\`\`json
{
  "variableCollections": [
    {
      "action": "CREATE",
      "id": "tempId_collection_default",
      "name": "Hex Core — Default",
      "initialModeId": "tempId_mode_light"
    }
  ],
  "variableModes": [
    {
      "action": "CREATE",
      "id": "tempId_mode_light",
      "name": "Light",
      "variableCollectionId": "tempId_collection_default"
    },
    {
      "action": "CREATE",
      "id": "tempId_mode_dark",
      "name": "Dark",
      "variableCollectionId": "tempId_collection_default"
    }
  ],
  "variables": [
    {
      "action": "CREATE",
      "id": "tempId_var_background",
      "name": "background",
      "variableCollectionId": "tempId_collection_default",
      "resolvedType": "COLOR"
    },
    {
      "action": "CREATE",
      "id": "tempId_var_primary",
      "name": "primary",
      "variableCollectionId": "tempId_collection_default",
      "resolvedType": "COLOR"
    },
    {
      "action": "CREATE",
      "id": "tempId_var_primary_foreground",
      "name": "primary-foreground",
      "variableCollectionId": "tempId_collection_default",
      "resolvedType": "COLOR"
    },
    {
      "action": "CREATE",
      "id": "tempId_var_radius",
      "name": "radius",
      "variableCollectionId": "tempId_collection_default",
      "resolvedType": "FLOAT"
    },
    {
      "action": "CREATE",
      "id": "tempId_var_duration_normal",
      "name": "duration-normal",
      "variableCollectionId": "tempId_collection_default",
      "resolvedType": "FLOAT"
    },
    {
      "action": "CREATE",
      "id": "tempId_var_space_4",
      "name": "space-4",
      "variableCollectionId": "tempId_collection_default",
      "resolvedType": "FLOAT"
    }
  ],
  "variableModeValues": [
    {
      "variableId": "tempId_var_background",
      "modeId": "tempId_mode_light",
      "value": {
        "r": 1,
        "g": 1,
        "b": 1
      }
    },
    {
      "variableId": "tempId_var_background",
      "modeId": "tempId_mode_dark",
      "value": {
        "r": 0.0351,
        "g": 0.0351,
        "b": 0.0429
      }
    },
    {
      "variableId": "tempId_var_primary",
      "modeId": "tempId_mode_light",
      "value": {
        "r": 0.0941,
        "g": 0.0941,
        "b": 0.1059
      }
    },
    {
      "variableId": "tempId_var_primary",
      "modeId": "tempId_mode_dark",
      "value": {
        "r": 0.98,
        "g": 0.98,
        "b": 0.98
      }
    },
    {
      "variableId": "tempId_var_primary_foreground",
      "modeId": "tempId_mode_light",
      "value": {
        "r": 0.98,
        "g": 0.98,
        "b": 0.98
      }
    },
    {
      "variableId": "tempId_var_primary_foreground",
      "modeId": "tempId_mode_dark",
      "value": {
        "r": 0.0941,
        "g": 0.0941,
        "b": 0.1059
      }
    },
    {
      "variableId": "tempId_var_radius",
      "modeId": "tempId_mode_light",
      "value": 8
    },
    {
      "variableId": "tempId_var_radius",
      "modeId": "tempId_mode_dark",
      "value": 8
    },
    {
      "variableId": "tempId_var_duration_normal",
      "modeId": "tempId_mode_light",
      "value": 200
    },
    {
      "variableId": "tempId_var_duration_normal",
      "modeId": "tempId_mode_dark",
      "value": 200
    },
    {
      "variableId": "tempId_var_space_4",
      "modeId": "tempId_mode_light",
      "value": 16
    },
    {
      "variableId": "tempId_var_space_4",
      "modeId": "tempId_mode_dark",
      "value": 16
    }
  ]
}
\`\`\`

## How to apply

\`\`\`bash
curl -X POST \\
  -H "X-Figma-Token: $FIGMA_PAT" \\
  -H "Content-Type: application/json" \\
  -d @hex-tokens.json \\
  https://api.figma.com/v1/files/$FILE_KEY/variables
\`\`\``;

const EXPECTED_UNKNOWN_THEME = `# Figma tokens — Hex Core

Generated by \`emit_figma_tokens\`. Paste the JSON below into Figma's \`POST /v1/files/:file_key/variables\` endpoint (or a Figma plugin that calls it) to populate a Variables collection that mirrors the theme.

**Unknown theme** \`vaporwave\` — fall back to \`default\` and notify the user. No JSON emitted.`;

interface Case {
	name: string;
	build: () => string;
	expected?: string;
	contains?: string[];
	excludes?: string[];
}

const CASES: Case[] = [
	{
		name: "happy path: 3 color + 3 non-color tokens, both modes",
		build: () => buildFigmaTokens({ theme: { requested: "default", resolved: fakeTheme } }),
		expected: EXPECTED_HAPPY,
	},
	{
		name: "unknown theme slug returns no-JSON message",
		build: () => buildFigmaTokens({ theme: { requested: "vaporwave", resolved: null } }),
		expected: EXPECTED_UNKNOWN_THEME,
	},
	{
		// Lock the unit-conversion contract: 1rem → 16, 0.5rem → 8, 200ms → 200,
		// 100% → 100, 1.5s → 1500. If a future palette adds a new unit, the
		// fall-through-to-zero branch in `parseFloatToken` would silently emit 0
		// for that token; this case proves we hit the documented branches.
		name: "unit-conversion gate (rem/ms/%/s/bare → Figma float)",
		build: () => {
			const t: FigmaTokensTheme = {
				name: "u",
				displayName: "U",
				tokens: {
					light: {
						a: { value: "1rem", type: "spacing" },
						b: { value: "0.5rem", type: "radius" },
						c: { value: "200ms", type: "duration" },
						d: { value: "100%", type: "dimension" },
						e: { value: "1.5s", type: "duration" },
						f: { value: "42", type: "dimension" },
					},
					dark: {
						a: { value: "1rem", type: "spacing" },
						b: { value: "0.5rem", type: "radius" },
						c: { value: "200ms", type: "duration" },
						d: { value: "100%", type: "dimension" },
						e: { value: "1.5s", type: "duration" },
						f: { value: "42", type: "dimension" },
					},
				},
			};
			return JSON.stringify(buildFigmaPayload(t).payload.variableModeValues);
		},
		contains: [
			'"value":16',
			'"value":8',
			'"value":200',
			'"value":100',
			'"value":1500',
			'"value":42',
		],
	},
	{
		// Regression gate for H2: dark-only keys must surface in the payload
		// (light-only iteration would silently drop them). Theme below has
		// `glow` only in dark — assert variable is created and the dark
		// mode-value is the only one emitted for that variable.
		name: "dark-only token lands in payload (asymmetry-bug regression gate)",
		build: () => {
			const t: FigmaTokensTheme = {
				name: "asym",
				displayName: "Asymmetric",
				tokens: {
					light: { primary: { value: "0 0% 100%", type: "color" } },
					dark: {
						primary: { value: "0 0% 0%", type: "color" },
						glow: { value: "300 100% 50%", type: "color" },
					},
				},
			};
			return JSON.stringify(buildFigmaPayload(t).payload);
		},
		contains: [
			'"name":"glow"',
			'"resolvedType":"COLOR"',
		],
	},
	{
		// Regression gate for H3: tokens whose `type` Figma can't represent
		// (shadow / gradient / cubicBezier) must be SKIPPED, not coerced to
		// FLOAT-0. Skipped slugs surface in the markdown header so designers
		// see what didn't transfer.
		name: "shadow/gradient/cubicBezier tokens are skipped, not coerced to FLOAT-0",
		build: () => {
			const t: FigmaTokensTheme = {
				name: "u",
				displayName: "U",
				tokens: {
					light: {
						primary: { value: "0 0% 100%", type: "color" },
						"shadow-sm": { value: "0 1px 2px rgba(0,0,0,0.1)", type: "shadow" },
						"gradient-hero": { value: "linear-gradient(180deg,#000,#fff)", type: "gradient" },
						"ease-out": { value: "0,0,0.2,1", type: "cubicBezier" },
					},
					dark: {
						primary: { value: "0 0% 0%", type: "color" },
						"shadow-sm": { value: "0 1px 2px rgba(0,0,0,0.4)", type: "shadow" },
						"gradient-hero": { value: "linear-gradient(180deg,#fff,#000)", type: "gradient" },
						"ease-out": { value: "0,0,0.2,1", type: "cubicBezier" },
					},
				},
			};
			return buildFigmaTokens({ theme: { requested: "u", resolved: t } });
		},
		contains: [
			'"name": "primary"',
			"`shadow-sm` (`shadow`)",
			"`gradient-hero` (`gradient`)",
			"`ease-out` (`cubicBezier`)",
		],
		excludes: [
			'"name": "shadow-sm"',
			'"name": "gradient-hero"',
			// shadow/gradient must not appear as FLOAT 0 — assert the
			// coerce-to-zero bug doesn't slip through.
			'"name": "shadow-sm",\n      "variableCollectionId',
		],
	},
	{
		// Regression gate for M1: empty palette → no JSON block emitted, with
		// a "no variables" inline notice. Caller doesn't accidentally POST an
		// empty collection.
		name: "empty palette → no JSON block, inline 'no variables' notice",
		build: () => {
			const t: FigmaTokensTheme = {
				name: "empty",
				displayName: "Empty",
				tokens: { light: {}, dark: {} },
			};
			return buildFigmaTokens({ theme: { requested: "empty", resolved: t } });
		},
		contains: ["**No variables emitted**"],
		excludes: [
			'"variableCollections"',
			"```json",
		],
	},
];

const failures: string[] = [];

for (const c of CASES) {
	const actual = c.build();
	if (c.expected !== undefined && actual !== c.expected) {
		failures.push(c.name);
		console.error(`\n--- FAIL: ${c.name} ---`);
		console.error("Expected:");
		console.error(c.expected);
		console.error("\nActual:");
		console.error(actual);
		console.error("---");
		continue;
	}
	if (c.contains) {
		for (const needle of c.contains) {
			if (!actual.includes(needle)) {
				failures.push(`${c.name} (missing substring: ${needle})`);
				console.error(`\n--- FAIL: ${c.name} ---`);
				console.error(`Expected output to contain: ${needle}`);
				console.error("\nActual output:");
				console.error(actual);
				console.error("---");
			}
		}
	}
	if (c.excludes) {
		for (const needle of c.excludes) {
			if (actual.includes(needle)) {
				failures.push(`${c.name} (unexpected substring: ${needle})`);
				console.error(`\n--- FAIL: ${c.name} ---`);
				console.error(`Expected output NOT to contain: ${needle}`);
				console.error("\nActual output:");
				console.error(actual);
				console.error("---");
			}
		}
	}
}

if (failures.length > 0) {
	console.error(`\nfigma-tokens: ${failures.length} snapshot(s) failed`);
	process.exit(1);
}

console.error(`figma-tokens: ${CASES.length} snapshots passed`);
