/**
 * The demo harness `hex poc` ships inside every generated app.
 *
 * A POC is not just the frames — it is the frames *demoed*. Without a way to
 * reach the states that matter (a fresh workspace, a restricted role), a
 * reviewer only ever sees one screenshot's worth of the product, and the
 * states where a design actually fails stay invisible.
 *
 * The harness is one floating panel plus two cookies. Cookies rather than
 * query params on purpose: a selection has to survive clicking through to the
 * next frame, or it is not a demo, it is a deep link. The panel POSTs, the
 * cookie is written, the page reloads, and every Server Component re-renders
 * against the new selection.
 *
 * The vocabulary here is deliberately generic — `viewer | member | admin` and
 * three capabilities. A generated app is expected to extend it: add roles,
 * add capabilities, and scope real data through them the way the frames
 * already scope their empty state.
 */

import type { PocFile } from "./poc.js";

/**
 * Components the demo harness imports. Added to the POC's install closure so
 * the panel and the frames' empty states resolve.
 */
export const DEMO_COMPONENT_SLUGS = ["empty", "select"] as const;

/** Import specifier the frames read the active selection from. */
export const DEMO_SERVER_MODULE = "@/lib/demo-server";

const DEMO_VOCABULARY = `/**
 * The demo vocabulary — everything the demo panel controls.
 *
 * Client-safe on purpose: the panel needs the lists and the labels, and
 * nothing in this file can grant access. Reading the active selections happens
 * server-side in \`lib/demo-server.ts\`.
 *
 * Generated by \`hex poc\`. Extend it: add a role, give it capabilities, and
 * scope your data through \`can\` rather than through the role name.
 */

/* -------------------------------------------------------------------------- */
/* Roles                                                                      */
/* -------------------------------------------------------------------------- */

/** Every role, in escalating order of access. */
export const DEMO_ROLES = ["viewer", "member", "admin"] as const;

/** One of the demo perspectives. */
export type DemoRole = (typeof DEMO_ROLES)[number];

/** The role assumed when no demo cookie is set. */
export const DEFAULT_ROLE: DemoRole = "member";

/** Cookie the demo panel writes and every frame reads. */
export const ROLE_COOKIE = "hex-demo-role";

/** How each role is presented in the demo panel. */
export const ROLE_LABELS: Record<DemoRole, string> = {
	viewer: "Viewer",
	member: "Member",
	admin: "Admin",
};

/** One line explaining what changes when this role is selected. */
export const ROLE_SUMMARIES: Record<DemoRole, string> = {
	viewer: "Read-only, own records, no settings.",
	member: "The whole workspace, read-only settings.",
	admin: "Everything, plus editable settings.",
};

/**
 * What a role is allowed to see and do.
 *
 * Frames branch on these, never on the role name — so adding a role means
 * adding a row below, not editing a frame.
 */
export interface RoleCapabilities {
	/** See records belonging to other people, not just their own. */
	seeTeam: boolean;
	/** Reach settings frames at all. */
	seeSettings: boolean;
	/** Change settings rather than just read them. */
	editSettings: boolean;
}

/** Capabilities per role. */
export const ROLE_CAPABILITIES: Record<DemoRole, RoleCapabilities> = {
	viewer: { seeTeam: false, seeSettings: false, editSettings: false },
	member: { seeTeam: true, seeSettings: true, editSettings: false },
	admin: { seeTeam: true, seeSettings: true, editSettings: true },
};

/**
 * Narrow an untrusted string to a role.
 * @param value - Raw cookie or request-body value
 * @returns The matching role, or \`null\` when it is not one of {@link DEMO_ROLES}
 */
export function toDemoRole(value: string | null | undefined): DemoRole | null {
	if (!value) return null;
	return DEMO_ROLES.find((role) => role === value) ?? null;
}

/* -------------------------------------------------------------------------- */
/* Data state                                                                 */
/* -------------------------------------------------------------------------- */

/** The two data states every frame can be demoed in. */
export const DATA_STATES = ["filled", "empty"] as const;

/** Whether frames render with sample data or as a fresh workspace. */
export type DataState = (typeof DATA_STATES)[number];

/** The state assumed when no demo cookie is set. */
export const DEFAULT_STATE: DataState = "filled";

/** Cookie the demo panel writes and every frame reads. */
export const STATE_COOKIE = "hex-demo-state";

/** How each data state is presented in the demo panel. */
export const STATE_LABELS: Record<DataState, string> = {
	filled: "With data",
	empty: "Empty",
};

/**
 * Narrow an untrusted string to a data state.
 * @param value - Raw cookie or request-body value
 * @returns The matching state, or \`null\` when it is not one of {@link DATA_STATES}
 */
export function toDataState(value: string | null | undefined): DataState | null {
	if (!value) return null;
	return DATA_STATES.find((state) => state === value) ?? null;
}
`;

const DEMO_SERVER = `import { cookies } from "next/headers";
import {
	DEFAULT_ROLE,
	DEFAULT_STATE,
	ROLE_CAPABILITIES,
	ROLE_COOKIE,
	STATE_COOKIE,
	toDataState,
	toDemoRole,
	type DataState,
	type DemoRole,
	type RoleCapabilities,
} from "./demo";

/** Everything the demo panel currently has selected. */
export interface DemoContext {
	/** Who the app is being viewed as. */
	role: DemoRole;
	/** What that role is allowed to see and do. */
	can: RoleCapabilities;
	/** Whether frames render with sample data or as a fresh workspace. */
	state: DataState;
}

/**
 * Read what the demo panel last selected.
 *
 * Server-only by way of \`next/headers\`: the cookies stand in for a session, so
 * frames read them the way they would read a signed-in user — which is what
 * makes one panel re-render every frame rather than just itself.
 *
 * @returns The active role, its capabilities, and the data state
 */
export async function getDemoContext(): Promise<DemoContext> {
	const store = await cookies();
	const role = toDemoRole(store.get(ROLE_COOKIE)?.value) ?? DEFAULT_ROLE;
	const state = toDataState(store.get(STATE_COOKIE)?.value) ?? DEFAULT_STATE;
	return { role, can: ROLE_CAPABILITIES[role], state };
}
`;

const DEMO_ROUTE = `import { cookies } from "next/headers";
import { ROLE_COOKIE, STATE_COOKIE, toDataState, toDemoRole } from "@/lib/demo";

/**
 * Narrow a parsed JSON body to something indexable.
 * @param value - Anything \`JSON.parse\` produced
 * @returns \`true\` when the value has string-keyed properties to read
 */
function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null;
}

/**
 * Apply a demo-panel selection.
 *
 * Selections live in cookies rather than query params so a choice survives
 * navigation — clicking through to the next frame stays in the selected role
 * and data state. Both fields are optional so the panel can change one
 * dimension without restating the other; a body carrying neither is a mistake,
 * not a no-op.
 *
 * @param req - Request carrying \`{ role?, state? }\`
 * @returns \`{ ok: true }\`, or a 400 when nothing valid was selected
 */
export async function POST(req: Request): Promise<Response> {
	const body: unknown = await req.json().catch(() => null);
	const raw: Record<string, unknown> = isRecord(body) ? body : {};

	const role = toDemoRole(typeof raw.role === "string" ? raw.role : null);
	const state = toDataState(typeof raw.state === "string" ? raw.state : null);
	if (!role && !state) {
		return Response.json({ error: "invalid-selection" }, { status: 400 });
	}

	const store = await cookies();
	const options = { path: "/", sameSite: "lax" } as const;
	if (role) store.set(ROLE_COOKIE, role, options);
	if (state) store.set(STATE_COOKIE, state, options);

	return Response.json({ ok: true });
}
`;

const DEMO_CONTROLS = `"use client";

import * as React from "react";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import {
	DATA_STATES,
	DEMO_ROLES,
	ROLE_LABELS,
	ROLE_SUMMARIES,
	STATE_LABELS,
	toDataState,
	toDemoRole,
	type DataState,
	type DemoRole,
} from "@/lib/demo";

/** A demo-panel selection — one dimension at a time. */
type Selection = { role: DemoRole } | { state: DataState };

/** Props for {@link DemoControls}. */
export interface DemoControlsProps {
	/** Role currently rendered, read from the cookie by the layout. */
	role: DemoRole;
	/** Data state currently rendered, read from the cookie by the layout. */
	state: DataState;
}

/**
 * The demo panel — one fixed corner card holding every control for states you
 * cannot reach by clicking: who is viewing the app, and whether it has data.
 *
 * Applying a selection POSTs to the demo route, which writes the cookies, then
 * reloads on purpose: the frames are Server Components, so they re-render on
 * the server against the new selection.
 */
export function DemoControls({ role, state }: DemoControlsProps) {
	const [collapsed, setCollapsed] = React.useState(false);
	const [busy, setBusy] = React.useState(false);
	const [failed, setFailed] = React.useState(false);

	async function apply(selection: Selection) {
		if (busy) return;
		setBusy(true);
		setFailed(false);
		try {
			const res = await fetch("/api/demo", {
				method: "POST",
				headers: { "content-type": "application/json" },
				body: JSON.stringify(selection),
			});
			if (!res.ok) throw new Error(\`demo \${res.status}\`);
			// Stay on the frame being looked at — every frame demos the difference.
			window.location.reload();
		} catch {
			setFailed(true);
			setBusy(false);
		}
	}

	function selectRole(value: string) {
		// Radix hands back a raw string; narrow it against the closed vocabulary.
		const next = toDemoRole(value);
		if (next && next !== role) void apply({ role: next });
	}

	function selectState(value: DataState) {
		if (value !== state) void apply({ state: value });
	}

	return (
		<aside
			aria-label="Demo controls"
			className="fixed bottom-4 right-4 z-50 w-72 rounded-lg border border-border bg-popover text-popover-foreground shadow-md"
		>
			<div className="flex items-center justify-between px-4 py-2.5">
				<p className="text-xs font-medium uppercase tracking-[0.06em] text-muted-foreground">Demo</p>
				<button
					type="button"
					aria-expanded={!collapsed}
					aria-controls="demo-controls-body"
					aria-label={collapsed ? "Expand demo controls" : "Collapse demo controls"}
					onClick={() => setCollapsed((c) => !c)}
					className="flex size-6 items-center justify-center rounded-md text-muted-foreground transition-all duration-200 ease-out hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 active:scale-[0.98]"
				>
					<svg
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						strokeWidth="2"
						strokeLinecap="round"
						strokeLinejoin="round"
						aria-hidden="true"
						className={\`size-4 transition-transform duration-200 ease-out \${collapsed ? "rotate-180" : ""}\`}
					>
						<path d="m6 9 6 6 6-6" />
					</svg>
				</button>
			</div>
			{/*
			  * Kept mounted and hidden rather than unmounted: the toggle's
			  * \`aria-controls\` has to resolve to a real element in both states,
			  * and an unmounted id is invalid ARIA.
			  */}
			<div id="demo-controls-body" hidden={collapsed} aria-busy={busy} className="space-y-4 px-4 pb-4">
				<p className="text-xs leading-relaxed text-muted-foreground">
					Sample data, no backend. Both controls re-render every frame, so a choice holds while
					you click through the app.
				</p>

				<div className="space-y-1.5">
					<label htmlFor="demo-role-select" className="text-xs font-medium">
						Viewing as
					</label>
					<Select value={role} onValueChange={selectRole} disabled={busy}>
						<SelectTrigger id="demo-role-select">
							<SelectValue />
						</SelectTrigger>
						<SelectContent>
							{DEMO_ROLES.map((option) => (
								<SelectItem key={option} value={option}>
									{ROLE_LABELS[option]}
								</SelectItem>
							))}
						</SelectContent>
					</Select>
					<p className="text-xs leading-relaxed text-muted-foreground">{ROLE_SUMMARIES[role]}</p>
				</div>

				<div className="space-y-1.5">
					<p className="text-xs font-medium" id="demo-state-label">
						Data
					</p>
					<div
						role="group"
						aria-labelledby="demo-state-label"
						className="inline-flex w-full items-center gap-1 rounded-lg border border-border bg-muted/40 p-1"
					>
						{DATA_STATES.map((option) => (
							<button
								key={option}
								type="button"
								disabled={busy}
								aria-pressed={state === option}
								onClick={() => selectState(option)}
								className={[
									"flex-1 rounded-md px-2.5 py-1 text-xs font-medium transition-all duration-200 ease-out",
									"focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
									"active:scale-[0.98] disabled:pointer-events-none disabled:opacity-50",
									state === option
										? "bg-background text-foreground shadow-sm"
										: "text-muted-foreground hover:text-foreground",
								].join(" ")}
							>
								{STATE_LABELS[option]}
							</button>
						))}
					</div>
				</div>

				{busy && (
					<p className="text-xs text-muted-foreground" role="status">
						Applying&hellip;
					</p>
				)}
				{failed && (
					<p className="text-xs text-destructive" role="alert">
						Could not apply that selection.
					</p>
				)}
			</div>
		</aside>
	);
}
`;

/**
 * The demo harness files, identical for every generated app.
 * @returns Vocabulary, server reader, API route, and the panel component
 */
export function buildDemoFiles(): PocFile[] {
	return [
		{ path: "lib/demo.ts", content: DEMO_VOCABULARY },
		{ path: "lib/demo-server.ts", content: DEMO_SERVER },
		{ path: "app/api/demo/route.ts", content: DEMO_ROUTE },
		{ path: "components/demo-controls.tsx", content: DEMO_CONTROLS },
	];
}
