/**
 * Visual regression tests for every registry component, in light + dark.
 *
 * Strategy: the docs site at /docs/components/<slug> already mounts every
 * component as a live preview (registry-driven). We screenshot the
 * `[data-testid="component-preview"]` region — that scopes the diff to
 * the rendered component itself, so docs chrome / sidebar / nav churn
 * doesn't churn baselines.
 *
 * Baselines live under `e2e/visual.spec.ts-snapshots/` in git. Refresh
 * with `pnpm --filter docs test:visual:update` after intentional visual
 * changes. CI uploads `playwright-report/` as an artifact on diff failure.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { expect, test } from "@playwright/test";

interface RegistryItem {
	name: string;
	displayName: string;
}

interface RegistryIndex {
	items: RegistryItem[];
}

const REGISTRY_PATH = path.resolve(__dirname, "../../../registry/registry.json");
const registry = JSON.parse(fs.readFileSync(REGISTRY_PATH, "utf-8")) as RegistryIndex;

/**
 * Which registry items ship a live demo, derived from the demo map rather
 * than a hand-kept list.
 *
 * This was a hardcoded set of 42 slugs. Forty-one of them simply had no
 * demo file, so the list was a second, hand-maintained answer to a question
 * the filesystem already answers — and every new block meant remembering to
 * add another line.
 *
 * Items without a demo (motion-pro, transition, track, and the composed
 * page-section blocks that need sibling context to render meaningfully)
 * render no `<ComponentPreview>`, so there is no screenshot target. They
 * still get an axe-scan via the a11y audit, and the blocks are visually
 * pinned in context by the /landing, /app and /store showcase snapshots
 * below.
 */
const DEMO_MAP_PATH = path.resolve(__dirname, "../src/lib/demos.generated.tsx");

/**
 * Every slug that ships a demo, read from the generated demo map.
 *
 * Read as TEXT, not imported: importing it would drag the whole component
 * library through Playwright's Node resolver, which has no bundler to
 * satisfy the package's `exports` map. Parsing the committed artefact keeps
 * that out while still making this list and the docs' list the SAME list.
 *
 * An earlier version walked the filesystem for `*.demo.tsx` and claimed in a
 * comment that it applied "the same rule as scripts/build-barrels.ts". It did
 * not — the walk was recursive over both package trees, while the generator
 * reads component folders plus three named roots — so the two could disagree
 * with nothing to notice. More importantly, a demo deleted by accident simply
 * removed its own visual test: coverage fell and the suite still went green.
 *
 * Sourcing from the generated map fixes both. The map is regenerated by
 * `pnpm build` and CI diffs every `*.generated.*` file, so a dropped demo now
 * shows up as a deleted line in a reviewed diff rather than as silence.
 * @returns Slug → true for every demo the docs app can render
 */
function readDemoSlugs(): Set<string> {
	const source = fs.readFileSync(DEMO_MAP_PATH, "utf-8");
	const body = source.slice(source.indexOf("export const demos"));
	const found = new Set<string>();
	for (const m of body.matchAll(/^\t(?:([A-Za-z_$][\w$]*)|"([^"]+)"):/gm)) {
		const slug = m[1] ?? m[2];
		if (slug) found.add(slug);
	}
	// A regex over a generated file is only safe if it fails loudly when the
	// generator's output shape changes. Zero demos would silently skip the
	// entire per-component suite and still report success.
	if (found.size === 0) {
		throw new Error(
			`Parsed 0 demos from ${path.relative(process.cwd(), DEMO_MAP_PATH)}. ` +
				`The generated map's shape changed — update readDemoSlugs() in this file.`,
		);
	}
	return found;
}

const DEMO_SLUGS = readDemoSlugs();

const HAS_DEMO = (slug: string): boolean => DEMO_SLUGS.has(slug);

/**
 * Escape hatch for a slug that ships a demo but still cannot be diffed.
 *
 * Empty, and it should stay that way. Non-determinism has a better answer
 * than skipping: `calendar` renders the current month, and the suite pins
 * the page clock for it via {@link TIME_SENSITIVE} rather than dropping
 * the coverage. Add an entry only with the reason inline.
 */
const SKIP_DESPITE_DEMO = new Set<string>();

// Demos that read `new Date()` at render time churn their baselines daily:
// Calendar defaults to the current month and flags "today". For these we pin
// the page clock to a fixed instant (below) so the screenshot is deterministic.
const TIME_SENSITIVE = new Set(["calendar"]);

const themes = [
	{ name: "light", html: "" },
	{ name: "dark", html: "dark" },
] as const;

// Freezes anything time-based that would churn screenshots: animations,
// transitions, caret blink, smooth scroll. CSS-level only — no React state
// changes — so the rendered tree stays semantically identical.
const FREEZE_CSS = `
*, *::before, *::after {
	animation-duration: 0s !important;
	animation-delay: 0s !important;
	transition-duration: 0s !important;
	transition-delay: 0s !important;
	caret-color: transparent !important;
	scroll-behavior: auto !important;
}
`;

for (const { name: slug, displayName } of registry.items) {
	if (!HAS_DEMO(slug) || SKIP_DESPITE_DEMO.has(slug)) continue;
	for (const theme of themes) {
		test(`${slug} (${theme.name})`, async ({ page }) => {
			// Set the theme class BEFORE the page renders to avoid a flash.
			// next-themes reads localStorage on hydrate, so seeding it there
			// is the most reliable way to lock the rendered theme.
			await page.addInitScript((themeClass) => {
				try {
					localStorage.setItem("theme", themeClass || "light");
				} catch {
					// localStorage may be unavailable in some test contexts; the
					// classList fallback below covers it.
				}
			}, theme.html);

			// Pin the page clock for time-sensitive demos so the rendered date
			// and the "today" marker stay identical across runs. Set before
			// navigation so the very first render already sees the frozen time;
			// scoped per-slug so the other baselines (captured under real time)
			// are untouched. Live docs keep showing the real month — only the
			// test's view of "now" is frozen.
			if (TIME_SENSITIVE.has(slug)) {
				await page.clock.setFixedTime(new Date("2026-06-10T12:00:00Z"));
			}

			await page.goto(`/docs/components/${slug}`, { waitUntil: "networkidle" });
			await page.addStyleTag({ content: FREEZE_CSS });
			await page.evaluate((cls) => {
				const html = document.documentElement;
				if (cls) html.classList.add(cls);
				else html.classList.remove("dark");
			}, theme.html);

			// Most pages render multiple <ComponentPreview /> instances — one
			// inline preview at the top of the page, plus one per additional
			// example below. We screenshot only the first (the inline preview)
			// so baselines stay deterministic per component, regardless of how
			// many examples a future docs author adds.
			const preview = page.getByTestId("component-preview").first();
			await expect(preview).toBeVisible({ timeout: 30_000 });

			// `toBeVisible` proves only that the TabsContent shell mounted —
			// `min-h-[200px]` satisfies the visibility check even before the
			// children paint. Anchor on an interactive descendant so Radix
			// `asChild`/Slot clones have finished merging onto trigger buttons;
			// otherwise dev-mode hydration races produce empty baselines (see
			// the alert-dialog dark mid-hydration regression). Slot merge is
			// sub-second on hydration — a tight 2s window is enough to bridge
			// the race without blowing the per-test budget when a primitive
			// has no interactive descendant (aspect-ratio, separator, etc.).
			await preview
				.locator("button, [role='button'], a, input, textarea, select, [tabindex]")
				.first()
				.waitFor({ state: "visible", timeout: 2_000 })
				.catch(() => {
					// Non-interactive primitives fall through; the outer
					// toBeVisible already guards them.
				});

			await expect(preview).toHaveScreenshot(`${slug}-${theme.name}.png`, {
				maxDiffPixelRatio: 0.01,
				animations: "disabled",
			});

			// Echo a stable label so logs are greppable per slug.
			test.info().annotations.push({ type: "component", description: `${displayName} (${theme.name})` });
		});
	}
}

/**
 * Page-level showcase snapshots. The composed section blocks (excluded from
 * the per-component loop above) are rendered in real context here — a full
 * landing page, app dashboard, and storefront — so a visual diff catches any
 * regression in how the blocks compose, not just how they render in isolation.
 */
const SHOWCASES = [
	{ slug: "showcase-landing", route: "/landing" },
	{ slug: "showcase-app", route: "/app" },
	{ slug: "showcase-store", route: "/store" },
	{ slug: "showcase-about", route: "/about" },
	{ slug: "showcase-order", route: "/order" },
	{ slug: "showcase-checkout", route: "/checkout" },
	{ slug: "showcase-pricing", route: "/pricing" },
	{ slug: "showcase-product", route: "/product" },
] as const;

for (const { slug, route } of SHOWCASES) {
	for (const theme of themes) {
		test(`${slug} (${theme.name})`, async ({ page }) => {
			await page.addInitScript((themeClass) => {
				try {
					localStorage.setItem("theme", themeClass || "light");
				} catch {
					/* classList fallback below */
				}
			}, theme.html);

			await page.goto(route, { waitUntil: "networkidle" });
			await page.addStyleTag({ content: FREEZE_CSS });
			await page.evaluate((cls) => {
				const html = document.documentElement;
				if (cls) html.classList.add(cls);
				else html.classList.remove("dark");
			}, theme.html);

			// Same hydration anchor as the per-component loop, same 2s budget.
			await page
				.locator("button, [role='button'], a")
				.first()
				.waitFor({ state: "visible", timeout: 2_000 })
				.catch(() => {
					// Showcases without any interactive surface fall through
					// (none today, but keeps the guard backward-compatible).
				});

			await expect(page).toHaveScreenshot(`${slug}-${theme.name}.png`, {
				fullPage: true,
				maxDiffPixelRatio: 0.01,
				animations: "disabled",
			});
		});
	}
}
