/**
 * Snapshot test for `buildAppContext`. Runs as a standalone node script via
 * `pnpm -F \`@hex-core/mcp\` test:app-context`. No test runner — the function
 * is pure and a format change should fail loudly here so it can be reviewed
 * deliberately.
 *
 * To update the snapshot: run the test, copy the actual output from stderr,
 * and replace EXPECTED below. Treat each update as a public-API change to
 * the LLM payload format and bump the changeset accordingly.
 *
 * All output (success AND failure) writes to stderr; stdout stays empty so
 * piping this into another command stays clean. CI consumers should capture
 * stderr to see the pass/fail summary.
 */

import type { Recipe } from "./recipe-loader.js";
import type { RegistryItem } from "./registry-loader.js";
import { buildAppContext } from "./app-context.js";

const fakeButton: RegistryItem = {
	name: "button",
	displayName: "Button",
	description: "Refined button with subtle shadow and micro-interactions.",
	category: "component",
	version: "1.0.0",
	framework: "react",
	props: [],
	variants: [],
	slots: [],
	files: [],
	// Two deps: one resolves to a slug ("popover"), one is filtered out as
	// non-component ("lib/utils"). Locks both internalDepToSlug behaviors.
	dependencies: { internal: ["components/popover/popover", "lib/utils"], npm: [] },
	tokensUsed: [],
	examples: [],
	ai: {},
	tags: ["form", "interaction"],
};

const fakeCard: RegistryItem = {
	name: "card",
	displayName: "Card",
	description: "Surface with header, body, and footer slots.",
	category: "component",
	version: "1.0.0",
	framework: "react",
	props: [],
	variants: [],
	slots: [],
	files: [],
	dependencies: { internal: [], npm: [] },
	tokensUsed: [],
	examples: [],
	ai: {},
	tags: ["layout"],
};

const fakeRecipe: Recipe = {
	slug: "settings-page",
	title: "Settings page",
	summary: "Tabbed settings with section headers and a save button.",
	tags: ["form"],
	brief: "settings",
	steps: [
		{ component: "card", reason: "section container", role: "primary" },
		{ component: "button", reason: "save action", role: "supporting" },
	],
	checklist: [
		{
			id: "a11y-1",
			check: "Save button has descriptive label",
			severity: "blocker",
			source: "derived-a11y",
		},
	],
};

const fakeTheme = {
	name: "default",
	displayName: "Default",
	description: "A refined, neutral theme.",
	tokens: {
		light: {
			background: { value: "0 0% 100%", type: "color" },
			foreground: { value: "240 10% 3.9%", type: "color" },
			primary: { value: "240 5.9% 10%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			destructive: { value: "0 84% 60%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
		},
	},
};

const EXPECTED_HAPPY = `# App context — Hex UI

Generated by \`emit_app_context\`. Paste this into your LLM chat as project context.

## Theme

**Default** (\`default\`) — A refined, neutral theme.

| Token | Value |
|---|---|
| \`--background\` | \`0 0% 100%\` |
| \`--foreground\` | \`240 10% 3.9%\` |
| \`--primary\` | \`240 5.9% 10%\` |
| \`--primary-foreground\` | \`0 0% 98%\` |
| \`--destructive\` | \`0 84% 60%\` |
| \`--radius\` | \`0.5rem\` |

_Values are raw — wrap in \`hsl(...)\` when consuming via Tailwind v4 \`@theme\`._

## Components (2)

### Button \`button\`

Refined button with subtle shadow and micro-interactions.

Depends on: \`popover\`.

### Card \`card\`

Surface with header, body, and footer slots.

## Recipes (1)

### Settings page \`settings-page\`

Tabbed settings with section headers and a save button.

**Steps:**
1. \`card\` — section container _(primary)_
2. \`button\` — save action _(supporting)_

**Checklist:**
- [ ] Save button has descriptive label _(blocker)_

## Install

\`\`\`bash
npx @hex-core/cli@latest init
npx @hex-core/cli@latest add button card
\`\`\``;

const EXPECTED_MISSING_SLUGS = `# App context — Hex UI

Generated by \`emit_app_context\`. Paste this into your LLM chat as project context.

## Theme

**Unknown theme** \`vaporwave\` — fall back to \`default\` and notify the user.

## Components (1)

> Missing: \`zoltan\`.

### Card \`card\`

Surface with header, body, and footer slots.

## Install

\`\`\`bash
npx @hex-core/cli@latest init
npx @hex-core/cli@latest add card
\`\`\``;

const EXPECTED_RECIPES_ALL_MISSING = `# App context — Hex UI

Generated by \`emit_app_context\`. Paste this into your LLM chat as project context.

## Theme

**Default** (\`default\`) — A refined, neutral theme.

| Token | Value |
|---|---|
| \`--background\` | \`0 0% 100%\` |
| \`--foreground\` | \`240 10% 3.9%\` |
| \`--primary\` | \`240 5.9% 10%\` |
| \`--primary-foreground\` | \`0 0% 98%\` |
| \`--destructive\` | \`0 84% 60%\` |
| \`--radius\` | \`0.5rem\` |

_Values are raw — wrap in \`hsl(...)\` when consuming via Tailwind v4 \`@theme\`._

## Components (1)

### Card \`card\`

Surface with header, body, and footer slots.

## Recipes (0)

> Missing: \`ghost-recipe\`.

## Install

\`\`\`bash
npx @hex-core/cli@latest init
npx @hex-core/cli@latest add card
\`\`\``;

interface Case {
	name: string;
	build: () => string;
	expected: string;
}

const CASES: Case[] = [
	{
		name: "happy path: theme + 2 components + 1 recipe",
		build: () =>
			buildAppContext({
				theme: { requested: "default", resolved: fakeTheme },
				components: [
					{ slug: "button", item: fakeButton },
					{ slug: "card", item: fakeCard },
				],
				recipes: [{ slug: "settings-page", recipe: fakeRecipe }],
			}),
		expected: EXPECTED_HAPPY,
	},
	{
		name: "missing theme + missing component slug",
		build: () =>
			buildAppContext({
				theme: { requested: "vaporwave", resolved: null },
				components: [
					{ slug: "card", item: fakeCard },
					{ slug: "zoltan", item: null },
				],
				recipes: [],
			}),
		expected: EXPECTED_MISSING_SLUGS,
	},
	{
		name: "recipes supplied but all unknown",
		build: () =>
			buildAppContext({
				theme: { requested: "default", resolved: fakeTheme },
				components: [{ slug: "card", item: fakeCard }],
				recipes: [{ slug: "ghost-recipe", recipe: null }],
			}),
		expected: EXPECTED_RECIPES_ALL_MISSING,
	},
];

const failures: string[] = [];

for (const c of CASES) {
	const actual = c.build();
	if (actual !== c.expected) {
		failures.push(c.name);
		console.error(`\n--- FAIL: ${c.name} ---`);
		console.error("Expected:");
		console.error(c.expected);
		console.error("\nActual:");
		console.error(actual);
		console.error("---");
	}
}

if (failures.length > 0) {
	console.error(`\napp-context: ${failures.length} snapshot(s) failed`);
	process.exit(1);
}

console.error(`app-context: ${CASES.length} snapshots passed`);
