/**
 * `emit_app_context` tool — assemble a deterministic markdown payload that
 * describes the user's chosen theme, components, and recipes. Designed for
 * paste-into-LLM workflows: a downstream agent reads this once and has
 * enough surface to implement against the exact Hex UI stack the user
 * picked, without having to re-discover any of it.
 *
 * Pure function — no I/O. The tool handler in `index.ts` resolves slugs
 * via `getTheme` / `loadRegistryItem` / `loadRecipe`, then passes the
 * looked-up objects in. This keeps the function snapshot-testable.
 */

import type { Recipe } from "./recipe-loader.js";
import { internalDepToSlug, type RegistryItem } from "./registry-loader.js";

/** Subset of theme fields surfaced in the markdown payload. */
export interface AppContextTheme {
	name: string;
	displayName: string;
	description: string;
	tokens: { light: Record<string, { value: string; type: string }> };
}

/** One component slot in the input — the item is null when the slug was unknown. */
export interface AppContextComponentSlot {
	slug: string;
	item: RegistryItem | null;
}

/** One recipe slot in the input — the recipe is null when the slug was unknown. */
export interface AppContextRecipeSlot {
	slug: string;
	recipe: Recipe | null;
}

/** Inputs to `buildAppContext`. Theme can be null when the requested slug was unknown. */
export interface AppContextInput {
	theme: { requested: string; resolved: AppContextTheme | null };
	components: AppContextComponentSlot[];
	recipes: AppContextRecipeSlot[];
}

const HIGHLIGHTED_TOKENS = [
	"background",
	"foreground",
	"primary",
	"primary-foreground",
	"destructive",
	"radius",
] as const;

/**
 * Build a deterministic markdown payload describing the chosen Hex UI stack.
 * @param input - Resolved theme + component + recipe records (nulls signal "not found")
 * @returns Markdown string suitable for pasting as LLM context
 */
export function buildAppContext(input: AppContextInput): string {
	const lines: string[] = [];

	lines.push("# App context — Hex UI");
	lines.push("");
	lines.push("Generated by `emit_app_context`. Paste this into your LLM chat as project context.");
	lines.push("");

	// ─── Theme ───
	lines.push("## Theme");
	lines.push("");
	if (input.theme.resolved) {
		const t = input.theme.resolved;
		lines.push(`**${t.displayName}** (\`${t.name}\`) — ${t.description}`);
		lines.push("");
		lines.push("| Token | Value |");
		lines.push("|---|---|");
		for (const key of HIGHLIGHTED_TOKENS) {
			const tok = t.tokens.light[key];
			if (!tok) continue;
			lines.push(`| \`--${key}\` | \`${tok.value}\` |`);
		}
		lines.push("");
		lines.push(
			"_Values are raw — wrap in `hsl(...)` when consuming via Tailwind v4 `@theme`._",
		);
	} else {
		lines.push(
			`**Unknown theme** \`${input.theme.requested}\` — fall back to \`default\` and notify the user.`,
		);
	}
	lines.push("");

	// ─── Components ───
	const found = input.components.filter((c) => c.item !== null);
	const missing = input.components.filter((c) => c.item === null).map((c) => c.slug);
	lines.push(`## Components (${found.length})`);
	lines.push("");
	if (missing.length > 0) {
		lines.push(`> Missing: ${missing.map((s) => `\`${s}\``).join(", ")}.`);
		lines.push("");
	}
	for (const slot of found) {
		const item = slot.item as RegistryItem;
		lines.push(`### ${item.displayName} \`${item.name}\``);
		lines.push("");
		lines.push(item.description);
		// Resolve raw dep paths ("components/popover/popover") to clean slugs
		// ("popover"). Non-component deps like "lib/utils" return null and drop
		// out so the LLM context lists only navigable component slugs.
		const internal = (item.dependencies?.internal ?? [])
			.map((d) => internalDepToSlug(d))
			.filter((s): s is string => s !== null);
		if (internal.length > 0) {
			lines.push("");
			lines.push(`Depends on: ${internal.map((d) => `\`${d}\``).join(", ")}.`);
		}
		lines.push("");
	}

	// ─── Recipes ───
	if (input.recipes.length > 0) {
		const foundRecipes = input.recipes.filter((r) => r.recipe !== null);
		const missingRecipes = input.recipes.filter((r) => r.recipe === null).map((r) => r.slug);
		lines.push(`## Recipes (${foundRecipes.length})`);
		lines.push("");
		if (missingRecipes.length > 0) {
			lines.push(`> Missing: ${missingRecipes.map((s) => `\`${s}\``).join(", ")}.`);
			lines.push("");
		}
		for (const slot of foundRecipes) {
			const r = slot.recipe as Recipe;
			lines.push(`### ${r.title} \`${r.slug}\``);
			lines.push("");
			lines.push(r.summary);
			lines.push("");
			lines.push("**Steps:**");
			for (let i = 0; i < r.steps.length; i++) {
				const s = r.steps[i];
				lines.push(`${i + 1}. \`${s.component}\` — ${s.reason} _(${s.role})_`);
			}
			if (r.checklist.length > 0) {
				lines.push("");
				lines.push("**Checklist:**");
				for (const c of r.checklist) {
					lines.push(`- [ ] ${c.check} _(${c.severity})_`);
				}
			}
			lines.push("");
		}
	}

	// ─── Install ───
	const installSlugs = found.map((c) => (c.item as RegistryItem).name);
	lines.push("## Install");
	lines.push("");
	lines.push("```bash");
	lines.push("npx @hex-core/cli@latest init");
	if (installSlugs.length > 0) {
		lines.push(`npx @hex-core/cli@latest add ${installSlugs.join(" ")}`);
	}
	lines.push("```");

	return lines.join("\n");
}
