import type { Theme } from "@hex-core/registry";
import { sharedTokens } from "./shared.js";

export const defaultTheme: Theme = {
	name: "default",
	displayName: "Default",
	description:
		"A modern, elegant minimalism — restrained cool-hue grayscale (~222 family) with a graphite primary and tight 0.375rem radius. Designed to recede so content leads; the cool slate carries identity across light + dark.",
	tokens: {
		light: {
			background: { value: "210 20% 98%", type: "color" },
			foreground: { value: "222 30% 11%", type: "color" },
			card: { value: "210 20% 98%", type: "color" },
			"card-foreground": { value: "222 30% 11%", type: "color" },
			popover: { value: "210 20% 98%", type: "color" },
			"popover-foreground": { value: "222 30% 11%", type: "color" },
			primary: { value: "222 25% 18%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "222 5% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 10% 3.9%", type: "color" },
			muted: { value: "222 5% 95.9%", type: "color" },
			"muted-foreground": { value: "222 8% 38%", type: "color" },
			accent: { value: "222 5% 95.9%", type: "color" },
			"accent-foreground": { value: "240 10% 3.9%", type: "color" },
			destructive: { value: "0 65% 50%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "222 8% 90%", type: "color" },
			input: { value: "222 8% 90%", type: "color" },
			ring: { value: "222 25% 18%", type: "color" },
			radius: { value: "0.375rem", type: "radius" },
			...sharedTokens,
		},
		dark: {
			background: { value: "210 15% 2%", type: "color" },
			foreground: { value: "222 22.5% 89%", type: "color" },
			card: { value: "210 15% 8%", type: "color" },
			popover: { value: "210 15% 8%", type: "color" },
			primary: { value: "222 30% 60%", type: "color" },
			secondary: { value: "222 8% 12%", type: "color" },
			muted: { value: "222 8% 12%", type: "color" },
			accent: { value: "222 8% 12%", type: "color" },
			destructive: { value: "0 48.8% 50%", type: "color" },
			border: { value: "222 8% 14%", type: "color" },
			input: { value: "222 8% 14%", type: "color" },
			ring: { value: "222 30% 60%", type: "color" },
			radius: { value: "0.375rem", type: "radius" },
			"card-foreground": { value: "222 22.5% 89%", type: "color" },
			"popover-foreground": { value: "222 22.5% 89%", type: "color" },
			"primary-foreground": { value: "210 15% 8%", type: "color" },
			"secondary-foreground": { value: "222 22.5% 89%", type: "color" },
			"muted-foreground": { value: "222 8% 65%", type: "color" },
			"accent-foreground": { value: "222 22.5% 89%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			...sharedTokens,
		},
	},
};
