import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
// Imported from source, not from the package name: this script runs as part
// of `pnpm build` *before* `turbo build`, so `packages/tokens/dist` does not
// exist yet on a clean checkout. Same convention as `scripts/build-graph.ts`.
import { defaultTheme, generateThemeCssV4 } from "../packages/tokens/src/index.js";

/**
 * Emit the docs site's colour layer from `@hex-core/tokens`.
 *
 * The docs `globals.css` used to hand-write the full palette four times —
 * `:root` triplets, the `@theme` bridge, and both again under `.dark` —
 * while `packages/tokens/src/themes/default.ts` held a fifth and sixth
 * copy and the theming page a seventh. The file carried a "KEEP IN SYNC"
 * comment admitting it.
 *
 * Meanwhile `hex theme init` already generated this exact output for
 * consumers. The shipping surface and the demoed surface could drift, and
 * a WCAG gate ran against both. Now they come from one generator.
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "apps/docs/src/app/tokens.generated.css");

const BANNER = `/*
 * AUTO-GENERATED by scripts/build-tokens.ts — do not edit.
 *
 * Source of truth: packages/tokens/src/themes/default.ts
 * Regenerate with \`pnpm run build:tokens\` (or \`pnpm build\`).
 */
`;

const content = `${BANNER}\n${generateThemeCssV4(defaultTheme)}\n`;

const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf-8") : null;
if (existing === content) {
	console.log(`  = ${path.relative(ROOT, OUT)}`);
} else {
	fs.writeFileSync(OUT, content);
	console.log(`  → ${path.relative(ROOT, OUT)}`);
}

const paletteSize = Object.keys(defaultTheme.palette ?? {}).length;
console.log(`\n✓ Tokens built from "${defaultTheme.name}" (${String(paletteSize)} ramp entries)`);
