// AUTO-GENERATED by scripts/build-barrels.ts — do not edit.
// Run `pnpm run build:barrels` (or `pnpm build`) to regenerate.

import type { ComponentType } from "react";
import { AccordionDemo } from "../../../../packages/components/src/components/accordion/accordion.demo";
import { AlertDemo } from "../../../../packages/components/src/components/alert/alert.demo";
import { AlertDialogDemo } from "../../../../packages/components/src/components/alert-dialog/alert-dialog.demo";
import { ArcDemo } from "../../../../packages/components/src/artifacts/arc/arc.demo";
import { AspectRatioDemo } from "../../../../packages/components/src/primitives/aspect-ratio/aspect-ratio.demo";
import { AttachmentDemo } from "../../../../packages/components/src/ai/attachment/attachment.demo";
import { AudioPlayerDemo } from "../../../../packages/components/src/ai/audio-player/audio-player.demo";
import { AudioWaveformDemo } from "../../../../packages/components/src/ai/audio-waveform/audio-waveform.demo";
import { AuthForgotPasswordDemo } from "../../../../packages/components/src/blocks/auth-forgot-password/auth-forgot-password.demo";
import { AuthResetPasswordDemo } from "../../../../packages/components/src/blocks/auth-reset-password/auth-reset-password.demo";
import { AuthSignInSplitDemo } from "../../../../packages/components/src/blocks/auth-sign-in-split/auth-sign-in-split.demo";
import { AuthSignUpCardDemo } from "../../../../packages/components/src/blocks/auth-sign-up-card/auth-sign-up-card.demo";
import { AuthVerifyEmailDemo } from "../../../../packages/components/src/blocks/auth-verify-email/auth-verify-email.demo";
import { AuthVerifyOtpDemo } from "../../../../packages/components/src/blocks/auth-verify-otp/auth-verify-otp.demo";
import { AvatarDemo } from "../../../../packages/components/src/primitives/avatar/avatar.demo";
import { BadgeDemo } from "../../../../packages/components/src/primitives/badge/badge.demo";
import { BlurInDemo } from "../../../../packages/motion/src/components/blur-in/blur-in.demo";
import { BounceDemo } from "../../../../packages/motion/src/components/bounce/bounce.demo";
import { BranchDemo } from "../../../../packages/components/src/ai/branch/branch.demo";
import { BreadcrumbDemo } from "../../../../packages/components/src/components/breadcrumb/breadcrumb.demo";
import { ButtonDemo } from "../../../../packages/components/src/primitives/button/button.demo";
import { CalendarDemo } from "../../../../packages/components/src/components/calendar/calendar.demo";
import { CanvasDemo } from "../../../../packages/components/src/ai/canvas/canvas.demo";
import { CardDemo } from "../../../../packages/components/src/components/card/card.demo";
import { ChainOfThoughtDemo } from "../../../../packages/components/src/ai/chain-of-thought/chain-of-thought.demo";
import { CheckboxDemo } from "../../../../packages/components/src/primitives/checkbox/checkbox.demo";
import { ChordDemo } from "../../../../packages/components/src/artifacts/chord/chord.demo";
import { CitationDemo } from "../../../../packages/components/src/ai/citation/citation.demo";
import { ClipDemo } from "../../../../packages/motion/src/schemas/clip.demo";
import { ClozeDemo } from "../../../../packages/components/src/artifacts/cloze/cloze.demo";
import { ClusterDemo } from "../../../../packages/components/src/primitives/cluster/cluster.demo";
import { CodeBlockDemo } from "../../../../packages/components/src/ai/code-block/code-block.demo";
import { CollapsibleDemo } from "../../../../packages/components/src/components/collapsible/collapsible.demo";
import { ColorPickerDemo } from "../../../../packages/components/src/components/color-picker/color-picker.demo";
import { ComboboxDemo } from "../../../../packages/components/src/components/combobox/combobox.demo";
import { CommandDemo } from "../../../../packages/components/src/components/command/command.demo";
import { CompareTableDemo } from "../../../../packages/components/src/artifacts/compare-table/compare-table.demo";
import { ComposerDemo } from "../../../../packages/components/src/ai/composer/composer.demo";
import { ContainerDemo } from "../../../../packages/components/src/primitives/container/container.demo";
import { ContextMenuDemo } from "../../../../packages/components/src/components/context-menu/context-menu.demo";
import { ConversationDemo } from "../../../../packages/components/src/ai/conversation/conversation.demo";
import { CountUpDemo } from "../../../../packages/motion/src/components/count-up/count-up.demo";
import { DataTableDemo } from "../../../../packages/components/src/components/data-table/data-table.demo";
import { DatePickerDemo } from "../../../../packages/components/src/components/date-picker/date-picker.demo";
import { DeckDemo } from "../../../../packages/components/src/artifacts/deck/deck.demo";
import { DendrogramDemo } from "../../../../packages/components/src/artifacts/dendrogram/dendrogram.demo";
import { DiagramDemo } from "../../../../packages/components/src/ai/diagram/diagram.demo";
import { DialogDemo } from "../../../../packages/components/src/components/dialog/dialog.demo";
import { SortableCardsDemo } from "../../../../packages/components/src/components/dnd/dnd.demo";
import { DrawerDemo } from "../../../../packages/components/src/components/drawer/drawer.demo";
import { DropdownMenuDemo } from "../../../../packages/components/src/components/dropdown-menu/dropdown-menu.demo";
import { DropzoneDemo } from "../../../../packages/components/src/components/dropzone/dropzone.demo";
import { EmptyDemo } from "../../../../packages/components/src/primitives/empty/empty.demo";
import { ErrorStateDemo } from "../../../../packages/components/src/primitives/error-state/error-state.demo";
import { FadeInDemo } from "../../../../packages/motion/src/components/fade-in/fade-in.demo";
import { FileTreeDemo } from "../../../../packages/components/src/components/file-tree/file-tree.demo";
import { FlashcardDemo } from "../../../../packages/components/src/artifacts/flashcard/flashcard.demo";
import { FlowchartDemo } from "../../../../packages/components/src/artifacts/flowchart/flowchart.demo";
import { FormDemo } from "../../../../packages/components/src/components/form/form.demo";
import { FunnelDemo } from "../../../../packages/components/src/artifacts/funnel/funnel.demo";
import { GanttDemo } from "../../../../packages/components/src/artifacts/gantt/gantt.demo";
import { GridDemo } from "../../../../packages/components/src/primitives/grid/grid.demo";
import { HoverCardDemo } from "../../../../packages/components/src/components/hover-card/hover-card.demo";
import { ImageOcclusionDemo } from "../../../../packages/components/src/artifacts/image-occlusion/image-occlusion.demo";
import { InlineCitationDemo } from "../../../../packages/components/src/ai/inline-citation/inline-citation.demo";
import { InputDemo } from "../../../../packages/components/src/primitives/input/input.demo";
import { InputOTPDemo } from "../../../../packages/components/src/components/input-otp/input-otp.demo";
import { KanbanDemo } from "../../../../packages/components/src/components/kanban/kanban.demo";
import { LabelDemo } from "../../../../packages/components/src/primitives/label/label.demo";
import { LoadingDemo } from "../../../../packages/components/src/primitives/loading/loading.demo";
import { LoadingIndicatorDemo } from "../../../../packages/components/src/ai/loading-indicator/loading-indicator.demo";
import { MarkdownDemo } from "../../../../packages/components/src/ai/markdown/markdown.demo";
import { MarqueeDemo } from "../../../../packages/motion/src/components/marquee/marquee.demo";
import { MatrixDemo } from "../../../../packages/components/src/artifacts/matrix/matrix.demo";
import { MenubarDemo } from "../../../../packages/components/src/components/menubar/menubar.demo";
import { MessageDemo } from "../../../../packages/components/src/ai/message/message.demo";
import { MessageActionsDemo } from "../../../../packages/components/src/ai/message-actions/message-actions.demo";
import { MessageListDemo } from "../../../../packages/components/src/ai/message-list/message-list.demo";
import { MindMapDemo } from "../../../../packages/components/src/artifacts/mind-map/mind-map.demo";
import { MotionDemo } from "../../../../packages/motion/src/schemas/motion.demo";
import { MotionTimelineDemo } from "../../../../packages/motion/src/schemas/motion-timeline.demo";
import { MultiComboboxDemo } from "../../../../packages/components/src/components/multi-combobox/multi-combobox.demo";
import { NavigationMenuDemo } from "../../../../packages/components/src/components/navigation-menu/navigation-menu.demo";
import { OrgChartDemo } from "../../../../packages/components/src/artifacts/org-chart/org-chart.demo";
import { PageTransitionDemo } from "../../../../packages/motion/src/components/page-transition/page-transition.demo";
import { PaginationDemo } from "../../../../packages/components/src/components/pagination/pagination.demo";
import { ParallaxDemo } from "../../../../packages/motion/src/components/parallax/parallax.demo";
import { PlanDemo } from "../../../../packages/components/src/ai/plan/plan.demo";
import { PopoverDemo } from "../../../../packages/components/src/components/popover/popover.demo";
import { PresenceDemo } from "../../../../packages/motion/src/schemas/presence.demo";
import { ProgressDemo } from "../../../../packages/components/src/primitives/progress/progress.demo";
import { PulseDemo } from "../../../../packages/motion/src/components/pulse/pulse.demo";
import { PyramidDemo } from "../../../../packages/components/src/artifacts/pyramid/pyramid.demo";
import { QuizDemo } from "../../../../packages/components/src/artifacts/quiz/quiz.demo";
import { RadioGroupDemo } from "../../../../packages/components/src/primitives/radio-group/radio-group.demo";
import { ReasoningDemo } from "../../../../packages/components/src/ai/reasoning/reasoning.demo";
import { ResizableDemo } from "../../../../packages/components/src/components/resizable/resizable.demo";
import { RevealOnScrollDemo } from "../../../../packages/motion/src/components/reveal-on-scroll/reveal-on-scroll.demo";
import { SankeyDemo } from "../../../../packages/components/src/artifacts/sankey/sankey.demo";
import { ScaleInDemo } from "../../../../packages/motion/src/components/scale-in/scale-in.demo";
import { SceneDemo } from "../../../../packages/motion/src/schemas/scene.demo";
import { ScrollAreaDemo } from "../../../../packages/components/src/primitives/scroll-area/scroll-area.demo";
import { SelectDemo } from "../../../../packages/components/src/primitives/select/select.demo";
import { SeparatorDemo } from "../../../../packages/components/src/primitives/separator/separator.demo";
import { SequenceDemo } from "../../../../packages/components/src/artifacts/sequence/sequence.demo";
import { ShakeDemo } from "../../../../packages/motion/src/components/shake/shake.demo";
import { SheetDemo } from "../../../../packages/components/src/components/sheet/sheet.demo";
import { ShimmerDemo } from "../../../../packages/components/src/ai/shimmer/shimmer.demo";
import { ShineDemo } from "../../../../packages/motion/src/components/shine/shine.demo";
import { SidebarDemo } from "../../../../packages/components/src/components/sidebar/sidebar.demo";
import { SkeletonDemo } from "../../../../packages/components/src/primitives/skeleton/skeleton.demo";
import { SlideInDemo } from "../../../../packages/motion/src/components/slide-in/slide-in.demo";
import { SliderDemo } from "../../../../packages/components/src/primitives/slider/slider.demo";
import { SonnerDemo } from "../../../../packages/components/src/components/sonner/sonner.demo";
import { SourcesDemo } from "../../../../packages/components/src/ai/sources/sources.demo";
import { SpacedRepetitionDemo } from "../../../../packages/components/src/artifacts/spaced-repetition/spaced-repetition.demo";
import { SpacerDemo } from "../../../../packages/components/src/primitives/spacer/spacer.demo";
import { SpeechRecognitionDemo } from "../../../../packages/components/src/ai/speech-recognition/speech-recognition.demo";
import { StackDemo } from "../../../../packages/components/src/primitives/stack/stack.demo";
import { StaggerDemo } from "../../../../packages/motion/src/components/stagger/stagger.demo";
import { StepperDemo } from "../../../../packages/components/src/components/stepper/stepper.demo";
import { SuggestionDemo } from "../../../../packages/components/src/ai/suggestion/suggestion.demo";
import { SunburstDemo } from "../../../../packages/components/src/artifacts/sunburst/sunburst.demo";
import { SwitchDemo } from "../../../../packages/components/src/primitives/switch/switch.demo";
import { TableDemo } from "../../../../packages/components/src/components/table/table.demo";
import { TabsDemo } from "../../../../packages/components/src/components/tabs/tabs.demo";
import { TagDemo } from "../../../../packages/components/src/primitives/tag/tag.demo";
import { TaskDemo } from "../../../../packages/components/src/ai/task/task.demo";
import { TerminalDemo } from "../../../../packages/components/src/ai/terminal/terminal.demo";
import { TextareaDemo } from "../../../../packages/components/src/primitives/textarea/textarea.demo";
import { TimeAxisDemo } from "../../../../packages/components/src/artifacts/time-axis/time-axis.demo";
import { TimePickerDemo } from "../../../../packages/components/src/components/time-picker/time-picker.demo";
import { TimelineDemo } from "../../../../packages/components/src/components/timeline/timeline.demo";
import { ToggleDemo } from "../../../../packages/components/src/primitives/toggle/toggle.demo";
import { ToggleGroupDemo } from "../../../../packages/components/src/primitives/toggle-group/toggle-group.demo";
import { ToolCallDemo } from "../../../../packages/components/src/ai/tool-call/tool-call.demo";
import { ToolbarDemo } from "../../../../packages/components/src/components/toolbar/toolbar.demo";
import { TooltipDemo } from "../../../../packages/components/src/components/tooltip/tooltip.demo";
import { TreeDemo } from "../../../../packages/components/src/components/tree/tree.demo";
import { TreeMapDemo } from "../../../../packages/components/src/artifacts/tree-map/tree-map.demo";
import { TypewriterDemo } from "../../../../packages/motion/src/components/typewriter/typewriter.demo";
import { UseAnimateDemo } from "../../../../packages/motion/src/schemas/use-animate.demo";
import { UseScrollDemo } from "../../../../packages/motion/src/schemas/use-scroll.demo";
import { VariantsDemo } from "../../../../packages/motion/src/schemas/variants.demo";
import { VennDemo } from "../../../../packages/components/src/artifacts/venn/venn.demo";

/** Map of component slug → rendered demo component. */
export const demos: Record<string, ComponentType> = {
	accordion: AccordionDemo,
	alert: AlertDemo,
	"alert-dialog": AlertDialogDemo,
	arc: ArcDemo,
	"aspect-ratio": AspectRatioDemo,
	attachment: AttachmentDemo,
	"audio-player": AudioPlayerDemo,
	"audio-waveform": AudioWaveformDemo,
	"auth-forgot-password": AuthForgotPasswordDemo,
	"auth-reset-password": AuthResetPasswordDemo,
	"auth-sign-in-split": AuthSignInSplitDemo,
	"auth-sign-up-card": AuthSignUpCardDemo,
	"auth-verify-email": AuthVerifyEmailDemo,
	"auth-verify-otp": AuthVerifyOtpDemo,
	avatar: AvatarDemo,
	badge: BadgeDemo,
	"blur-in": BlurInDemo,
	bounce: BounceDemo,
	branch: BranchDemo,
	breadcrumb: BreadcrumbDemo,
	button: ButtonDemo,
	calendar: CalendarDemo,
	canvas: CanvasDemo,
	card: CardDemo,
	"chain-of-thought": ChainOfThoughtDemo,
	checkbox: CheckboxDemo,
	chord: ChordDemo,
	citation: CitationDemo,
	clip: ClipDemo,
	cloze: ClozeDemo,
	cluster: ClusterDemo,
	"code-block": CodeBlockDemo,
	collapsible: CollapsibleDemo,
	"color-picker": ColorPickerDemo,
	combobox: ComboboxDemo,
	command: CommandDemo,
	"compare-table": CompareTableDemo,
	composer: ComposerDemo,
	container: ContainerDemo,
	"context-menu": ContextMenuDemo,
	conversation: ConversationDemo,
	"count-up": CountUpDemo,
	"data-table": DataTableDemo,
	"date-picker": DatePickerDemo,
	deck: DeckDemo,
	dendrogram: DendrogramDemo,
	diagram: DiagramDemo,
	dialog: DialogDemo,
	dnd: SortableCardsDemo,
	drawer: DrawerDemo,
	"dropdown-menu": DropdownMenuDemo,
	dropzone: DropzoneDemo,
	empty: EmptyDemo,
	"error-state": ErrorStateDemo,
	"fade-in": FadeInDemo,
	"file-tree": FileTreeDemo,
	flashcard: FlashcardDemo,
	flowchart: FlowchartDemo,
	form: FormDemo,
	funnel: FunnelDemo,
	gantt: GanttDemo,
	grid: GridDemo,
	"hover-card": HoverCardDemo,
	"image-occlusion": ImageOcclusionDemo,
	"inline-citation": InlineCitationDemo,
	input: InputDemo,
	"input-otp": InputOTPDemo,
	kanban: KanbanDemo,
	label: LabelDemo,
	loading: LoadingDemo,
	"loading-indicator": LoadingIndicatorDemo,
	markdown: MarkdownDemo,
	marquee: MarqueeDemo,
	matrix: MatrixDemo,
	menubar: MenubarDemo,
	message: MessageDemo,
	"message-actions": MessageActionsDemo,
	"message-list": MessageListDemo,
	"mind-map": MindMapDemo,
	motion: MotionDemo,
	"motion-timeline": MotionTimelineDemo,
	"multi-combobox": MultiComboboxDemo,
	"navigation-menu": NavigationMenuDemo,
	"org-chart": OrgChartDemo,
	"page-transition": PageTransitionDemo,
	pagination: PaginationDemo,
	parallax: ParallaxDemo,
	plan: PlanDemo,
	popover: PopoverDemo,
	presence: PresenceDemo,
	progress: ProgressDemo,
	pulse: PulseDemo,
	pyramid: PyramidDemo,
	quiz: QuizDemo,
	"radio-group": RadioGroupDemo,
	reasoning: ReasoningDemo,
	resizable: ResizableDemo,
	"reveal-on-scroll": RevealOnScrollDemo,
	sankey: SankeyDemo,
	"scale-in": ScaleInDemo,
	scene: SceneDemo,
	"scroll-area": ScrollAreaDemo,
	select: SelectDemo,
	separator: SeparatorDemo,
	sequence: SequenceDemo,
	shake: ShakeDemo,
	sheet: SheetDemo,
	shimmer: ShimmerDemo,
	shine: ShineDemo,
	sidebar: SidebarDemo,
	skeleton: SkeletonDemo,
	"slide-in": SlideInDemo,
	slider: SliderDemo,
	sonner: SonnerDemo,
	sources: SourcesDemo,
	"spaced-repetition": SpacedRepetitionDemo,
	spacer: SpacerDemo,
	"speech-recognition": SpeechRecognitionDemo,
	stack: StackDemo,
	stagger: StaggerDemo,
	stepper: StepperDemo,
	suggestion: SuggestionDemo,
	sunburst: SunburstDemo,
	switch: SwitchDemo,
	table: TableDemo,
	tabs: TabsDemo,
	tag: TagDemo,
	task: TaskDemo,
	terminal: TerminalDemo,
	textarea: TextareaDemo,
	"time-axis": TimeAxisDemo,
	"time-picker": TimePickerDemo,
	timeline: TimelineDemo,
	toggle: ToggleDemo,
	"toggle-group": ToggleGroupDemo,
	"tool-call": ToolCallDemo,
	toolbar: ToolbarDemo,
	tooltip: TooltipDemo,
	tree: TreeDemo,
	"tree-map": TreeMapDemo,
	typewriter: TypewriterDemo,
	"use-animate": UseAnimateDemo,
	"use-scroll": UseScrollDemo,
	variants: VariantsDemo,
	venn: VennDemo,
};

/**
 * Look up a demo component by registry slug.
 * @param slug - The component's registry name (e.g. "button")
 * @returns The demo component, or undefined if the component ships no demo
 */
export function getDemo(slug: string): ComponentType | undefined {
	return demos[slug];
}
